// Code generated by ent, DO NOT EDIT.

package flight

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the flight type in the database.
	Label = "flight"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrigin holds the string denoting the origin field in the database.
	FieldOrigin = "origin"
	// FieldDestination holds the string denoting the destination field in the database.
	FieldDestination = "destination"
	// FieldScheduledDeparture holds the string denoting the scheduled_departure field in the database.
	FieldScheduledDeparture = "scheduled_departure"
	// FieldScheduledArrival holds the string denoting the scheduled_arrival field in the database.
	FieldScheduledArrival = "scheduled_arrival"
	// FieldCloseBookingBufferNs holds the string denoting the close_booking_buffer_ns field in the database.
	FieldCloseBookingBufferNs = "close_booking_buffer_ns"
	// EdgeAircraft holds the string denoting the aircraft edge name in mutations.
	EdgeAircraft = "aircraft"
	// EdgeSeats holds the string denoting the seats edge name in mutations.
	EdgeSeats = "seats"
	// EdgeTickets holds the string denoting the tickets edge name in mutations.
	EdgeTickets = "tickets"
	// Table holds the table name of the flight in the database.
	Table = "flights"
	// AircraftTable is the table that holds the aircraft relation/edge.
	AircraftTable = "flights"
	// AircraftInverseTable is the table name for the Aircraft entity.
	// It exists in this package in order to avoid circular dependency with the "aircraft" package.
	AircraftInverseTable = "aircrafts"
	// AircraftColumn is the table column denoting the aircraft relation/edge.
	AircraftColumn = "aircraft_flights"
	// SeatsTable is the table that holds the seats relation/edge.
	SeatsTable = "flight_seats"
	// SeatsInverseTable is the table name for the FlightSeat entity.
	// It exists in this package in order to avoid circular dependency with the "flightseat" package.
	SeatsInverseTable = "flight_seats"
	// SeatsColumn is the table column denoting the seats relation/edge.
	SeatsColumn = "flight_id"
	// TicketsTable is the table that holds the tickets relation/edge.
	TicketsTable = "tickets"
	// TicketsInverseTable is the table name for the Ticket entity.
	// It exists in this package in order to avoid circular dependency with the "ticket" package.
	TicketsInverseTable = "tickets"
	// TicketsColumn is the table column denoting the tickets relation/edge.
	TicketsColumn = "flight_tickets"
)

// Columns holds all SQL columns for flight fields.
var Columns = []string{
	FieldID,
	FieldOrigin,
	FieldDestination,
	FieldScheduledDeparture,
	FieldScheduledArrival,
	FieldCloseBookingBufferNs,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "flights"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"aircraft_flights",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// OriginValidator is a validator for the "origin" field. It is called by the builders before save.
	OriginValidator func(string) error
	// DestinationValidator is a validator for the "destination" field. It is called by the builders before save.
	DestinationValidator func(string) error
)

// OrderOption defines the ordering options for the Flight queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrigin orders the results by the origin field.
func ByOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrigin, opts...).ToFunc()
}

// ByDestination orders the results by the destination field.
func ByDestination(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestination, opts...).ToFunc()
}

// ByScheduledDeparture orders the results by the scheduled_departure field.
func ByScheduledDeparture(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduledDeparture, opts...).ToFunc()
}

// ByScheduledArrival orders the results by the scheduled_arrival field.
func ByScheduledArrival(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduledArrival, opts...).ToFunc()
}

// ByCloseBookingBufferNs orders the results by the close_booking_buffer_ns field.
func ByCloseBookingBufferNs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCloseBookingBufferNs, opts...).ToFunc()
}

// ByAircraftField orders the results by aircraft field.
func ByAircraftField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAircraftStep(), sql.OrderByField(field, opts...))
	}
}

// BySeatsCount orders the results by seats count.
func BySeatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSeatsStep(), opts...)
	}
}

// BySeats orders the results by seats terms.
func BySeats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTicketsCount orders the results by tickets count.
func ByTicketsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTicketsStep(), opts...)
	}
}

// ByTickets orders the results by tickets terms.
func ByTickets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTicketsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAircraftStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AircraftInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AircraftTable, AircraftColumn),
	)
}
func newSeatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SeatsTable, SeatsColumn),
	)
}
func newTicketsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TicketsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TicketsTable, TicketsColumn),
	)
}
