// Code generated by ent, DO NOT EDIT.

package flight

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Flight {
	return predicate.Flight(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Flight {
	return predicate.Flight(sql.FieldContainsFold(FieldID, id))
}

// Origin applies equality check predicate on the "origin" field. It's identical to OriginEQ.
func Origin(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldOrigin, v))
}

// Destination applies equality check predicate on the "destination" field. It's identical to DestinationEQ.
func Destination(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldDestination, v))
}

// ScheduledDeparture applies equality check predicate on the "scheduled_departure" field. It's identical to ScheduledDepartureEQ.
func ScheduledDeparture(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldScheduledDeparture, v))
}

// ScheduledArrival applies equality check predicate on the "scheduled_arrival" field. It's identical to ScheduledArrivalEQ.
func ScheduledArrival(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldScheduledArrival, v))
}

// CloseBookingBufferNs applies equality check predicate on the "close_booking_buffer_ns" field. It's identical to CloseBookingBufferNsEQ.
func CloseBookingBufferNs(v int64) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldCloseBookingBufferNs, v))
}

// OriginEQ applies the EQ predicate on the "origin" field.
func OriginEQ(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldOrigin, v))
}

// OriginNEQ applies the NEQ predicate on the "origin" field.
func OriginNEQ(v string) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldOrigin, v))
}

// OriginIn applies the In predicate on the "origin" field.
func OriginIn(vs ...string) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldOrigin, vs...))
}

// OriginNotIn applies the NotIn predicate on the "origin" field.
func OriginNotIn(vs ...string) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldOrigin, vs...))
}

// OriginGT applies the GT predicate on the "origin" field.
func OriginGT(v string) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldOrigin, v))
}

// OriginGTE applies the GTE predicate on the "origin" field.
func OriginGTE(v string) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldOrigin, v))
}

// OriginLT applies the LT predicate on the "origin" field.
func OriginLT(v string) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldOrigin, v))
}

// OriginLTE applies the LTE predicate on the "origin" field.
func OriginLTE(v string) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldOrigin, v))
}

// OriginContains applies the Contains predicate on the "origin" field.
func OriginContains(v string) predicate.Flight {
	return predicate.Flight(sql.FieldContains(FieldOrigin, v))
}

// OriginHasPrefix applies the HasPrefix predicate on the "origin" field.
func OriginHasPrefix(v string) predicate.Flight {
	return predicate.Flight(sql.FieldHasPrefix(FieldOrigin, v))
}

// OriginHasSuffix applies the HasSuffix predicate on the "origin" field.
func OriginHasSuffix(v string) predicate.Flight {
	return predicate.Flight(sql.FieldHasSuffix(FieldOrigin, v))
}

// OriginEqualFold applies the EqualFold predicate on the "origin" field.
func OriginEqualFold(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEqualFold(FieldOrigin, v))
}

// OriginContainsFold applies the ContainsFold predicate on the "origin" field.
func OriginContainsFold(v string) predicate.Flight {
	return predicate.Flight(sql.FieldContainsFold(FieldOrigin, v))
}

// DestinationEQ applies the EQ predicate on the "destination" field.
func DestinationEQ(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldDestination, v))
}

// DestinationNEQ applies the NEQ predicate on the "destination" field.
func DestinationNEQ(v string) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldDestination, v))
}

// DestinationIn applies the In predicate on the "destination" field.
func DestinationIn(vs ...string) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldDestination, vs...))
}

// DestinationNotIn applies the NotIn predicate on the "destination" field.
func DestinationNotIn(vs ...string) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldDestination, vs...))
}

// DestinationGT applies the GT predicate on the "destination" field.
func DestinationGT(v string) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldDestination, v))
}

// DestinationGTE applies the GTE predicate on the "destination" field.
func DestinationGTE(v string) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldDestination, v))
}

// DestinationLT applies the LT predicate on the "destination" field.
func DestinationLT(v string) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldDestination, v))
}

// DestinationLTE applies the LTE predicate on the "destination" field.
func DestinationLTE(v string) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldDestination, v))
}

// DestinationContains applies the Contains predicate on the "destination" field.
func DestinationContains(v string) predicate.Flight {
	return predicate.Flight(sql.FieldContains(FieldDestination, v))
}

// DestinationHasPrefix applies the HasPrefix predicate on the "destination" field.
func DestinationHasPrefix(v string) predicate.Flight {
	return predicate.Flight(sql.FieldHasPrefix(FieldDestination, v))
}

// DestinationHasSuffix applies the HasSuffix predicate on the "destination" field.
func DestinationHasSuffix(v string) predicate.Flight {
	return predicate.Flight(sql.FieldHasSuffix(FieldDestination, v))
}

// DestinationEqualFold applies the EqualFold predicate on the "destination" field.
func DestinationEqualFold(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEqualFold(FieldDestination, v))
}

// DestinationContainsFold applies the ContainsFold predicate on the "destination" field.
func DestinationContainsFold(v string) predicate.Flight {
	return predicate.Flight(sql.FieldContainsFold(FieldDestination, v))
}

// ScheduledDepartureEQ applies the EQ predicate on the "scheduled_departure" field.
func ScheduledDepartureEQ(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldScheduledDeparture, v))
}

// ScheduledDepartureNEQ applies the NEQ predicate on the "scheduled_departure" field.
func ScheduledDepartureNEQ(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldScheduledDeparture, v))
}

// ScheduledDepartureIn applies the In predicate on the "scheduled_departure" field.
func ScheduledDepartureIn(vs ...time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldScheduledDeparture, vs...))
}

// ScheduledDepartureNotIn applies the NotIn predicate on the "scheduled_departure" field.
func ScheduledDepartureNotIn(vs ...time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldScheduledDeparture, vs...))
}

// ScheduledDepartureGT applies the GT predicate on the "scheduled_departure" field.
func ScheduledDepartureGT(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldScheduledDeparture, v))
}

// ScheduledDepartureGTE applies the GTE predicate on the "scheduled_departure" field.
func ScheduledDepartureGTE(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldScheduledDeparture, v))
}

// ScheduledDepartureLT applies the LT predicate on the "scheduled_departure" field.
func ScheduledDepartureLT(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldScheduledDeparture, v))
}

// ScheduledDepartureLTE applies the LTE predicate on the "scheduled_departure" field.
func ScheduledDepartureLTE(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldScheduledDeparture, v))
}

// ScheduledArrivalEQ applies the EQ predicate on the "scheduled_arrival" field.
func ScheduledArrivalEQ(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldScheduledArrival, v))
}

// ScheduledArrivalNEQ applies the NEQ predicate on the "scheduled_arrival" field.
func ScheduledArrivalNEQ(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldScheduledArrival, v))
}

// ScheduledArrivalIn applies the In predicate on the "scheduled_arrival" field.
func ScheduledArrivalIn(vs ...time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldScheduledArrival, vs...))
}

// ScheduledArrivalNotIn applies the NotIn predicate on the "scheduled_arrival" field.
func ScheduledArrivalNotIn(vs ...time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldScheduledArrival, vs...))
}

// ScheduledArrivalGT applies the GT predicate on the "scheduled_arrival" field.
func ScheduledArrivalGT(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldScheduledArrival, v))
}

// ScheduledArrivalGTE applies the GTE predicate on the "scheduled_arrival" field.
func ScheduledArrivalGTE(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldScheduledArrival, v))
}

// ScheduledArrivalLT applies the LT predicate on the "scheduled_arrival" field.
func ScheduledArrivalLT(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldScheduledArrival, v))
}

// ScheduledArrivalLTE applies the LTE predicate on the "scheduled_arrival" field.
func ScheduledArrivalLTE(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldScheduledArrival, v))
}

// CloseBookingBufferNsEQ applies the EQ predicate on the "close_booking_buffer_ns" field.
func CloseBookingBufferNsEQ(v int64) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldCloseBookingBufferNs, v))
}

// CloseBookingBufferNsNEQ applies the NEQ predicate on the "close_booking_buffer_ns" field.
func CloseBookingBufferNsNEQ(v int64) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldCloseBookingBufferNs, v))
}

// CloseBookingBufferNsIn applies the In predicate on the "close_booking_buffer_ns" field.
func CloseBookingBufferNsIn(vs ...int64) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldCloseBookingBufferNs, vs...))
}

// CloseBookingBufferNsNotIn applies the NotIn predicate on the "close_booking_buffer_ns" field.
func CloseBookingBufferNsNotIn(vs ...int64) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldCloseBookingBufferNs, vs...))
}

// CloseBookingBufferNsGT applies the GT predicate on the "close_booking_buffer_ns" field.
func CloseBookingBufferNsGT(v int64) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldCloseBookingBufferNs, v))
}

// CloseBookingBufferNsGTE applies the GTE predicate on the "close_booking_buffer_ns" field.
func CloseBookingBufferNsGTE(v int64) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldCloseBookingBufferNs, v))
}

// CloseBookingBufferNsLT applies the LT predicate on the "close_booking_buffer_ns" field.
func CloseBookingBufferNsLT(v int64) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldCloseBookingBufferNs, v))
}

// CloseBookingBufferNsLTE applies the LTE predicate on the "close_booking_buffer_ns" field.
func CloseBookingBufferNsLTE(v int64) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldCloseBookingBufferNs, v))
}

// HasAircraft applies the HasEdge predicate on the "aircraft" edge.
func HasAircraft() predicate.Flight {
	return predicate.Flight(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AircraftTable, AircraftColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAircraftWith applies the HasEdge predicate on the "aircraft" edge with a given conditions (other predicates).
func HasAircraftWith(preds ...predicate.Aircraft) predicate.Flight {
	return predicate.Flight(func(s *sql.Selector) {
		step := newAircraftStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSeats applies the HasEdge predicate on the "seats" edge.
func HasSeats() predicate.Flight {
	return predicate.Flight(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SeatsTable, SeatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeatsWith applies the HasEdge predicate on the "seats" edge with a given conditions (other predicates).
func HasSeatsWith(preds ...predicate.FlightSeat) predicate.Flight {
	return predicate.Flight(func(s *sql.Selector) {
		step := newSeatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTickets applies the HasEdge predicate on the "tickets" edge.
func HasTickets() predicate.Flight {
	return predicate.Flight(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TicketsTable, TicketsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketsWith applies the HasEdge predicate on the "tickets" edge with a given conditions (other predicates).
func HasTicketsWith(preds ...predicate.Ticket) predicate.Flight {
	return predicate.Flight(func(s *sql.Selector) {
		step := newTicketsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Flight) predicate.Flight {
	return predicate.Flight(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Flight) predicate.Flight {
	return predicate.Flight(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Flight) predicate.Flight {
	return predicate.Flight(sql.NotPredicates(p))
}
