// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/aircraft"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
)

// AircraftUpdate is the builder for updating Aircraft entities.
type AircraftUpdate struct {
	config
	hooks    []Hook
	mutation *AircraftMutation
}

// Where appends a list predicates to the AircraftUpdate builder.
func (_u *AircraftUpdate) Where(ps ...predicate.Aircraft) *AircraftUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSeats sets the "seats" field.
func (_u *AircraftUpdate) SetSeats(v []string) *AircraftUpdate {
	_u.mutation.SetSeats(v)
	return _u
}

// AppendSeats appends value to the "seats" field.
func (_u *AircraftUpdate) AppendSeats(v []string) *AircraftUpdate {
	_u.mutation.AppendSeats(v)
	return _u
}

// AddFlightIDs adds the "flights" edge to the Flight entity by IDs.
func (_u *AircraftUpdate) AddFlightIDs(ids ...string) *AircraftUpdate {
	_u.mutation.AddFlightIDs(ids...)
	return _u
}

// AddFlights adds the "flights" edges to the Flight entity.
func (_u *AircraftUpdate) AddFlights(v ...*Flight) *AircraftUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlightIDs(ids...)
}

// Mutation returns the AircraftMutation object of the builder.
func (_u *AircraftUpdate) Mutation() *AircraftMutation {
	return _u.mutation
}

// ClearFlights clears all "flights" edges to the Flight entity.
func (_u *AircraftUpdate) ClearFlights() *AircraftUpdate {
	_u.mutation.ClearFlights()
	return _u
}

// RemoveFlightIDs removes the "flights" edge to Flight entities by IDs.
func (_u *AircraftUpdate) RemoveFlightIDs(ids ...string) *AircraftUpdate {
	_u.mutation.RemoveFlightIDs(ids...)
	return _u
}

// RemoveFlights removes "flights" edges to Flight entities.
func (_u *AircraftUpdate) RemoveFlights(v ...*Flight) *AircraftUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlightIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AircraftUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AircraftUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AircraftUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AircraftUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AircraftUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(aircraft.Table, aircraft.Columns, sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Seats(); ok {
		_spec.SetField(aircraft.FieldSeats, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSeats(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, aircraft.FieldSeats, value)
		})
	}
	if _u.mutation.FlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlightsIDs(); len(nodes) > 0 && !_u.mutation.FlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aircraft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AircraftUpdateOne is the builder for updating a single Aircraft entity.
type AircraftUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AircraftMutation
}

// SetSeats sets the "seats" field.
func (_u *AircraftUpdateOne) SetSeats(v []string) *AircraftUpdateOne {
	_u.mutation.SetSeats(v)
	return _u
}

// AppendSeats appends value to the "seats" field.
func (_u *AircraftUpdateOne) AppendSeats(v []string) *AircraftUpdateOne {
	_u.mutation.AppendSeats(v)
	return _u
}

// AddFlightIDs adds the "flights" edge to the Flight entity by IDs.
func (_u *AircraftUpdateOne) AddFlightIDs(ids ...string) *AircraftUpdateOne {
	_u.mutation.AddFlightIDs(ids...)
	return _u
}

// AddFlights adds the "flights" edges to the Flight entity.
func (_u *AircraftUpdateOne) AddFlights(v ...*Flight) *AircraftUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlightIDs(ids...)
}

// Mutation returns the AircraftMutation object of the builder.
func (_u *AircraftUpdateOne) Mutation() *AircraftMutation {
	return _u.mutation
}

// ClearFlights clears all "flights" edges to the Flight entity.
func (_u *AircraftUpdateOne) ClearFlights() *AircraftUpdateOne {
	_u.mutation.ClearFlights()
	return _u
}

// RemoveFlightIDs removes the "flights" edge to Flight entities by IDs.
func (_u *AircraftUpdateOne) RemoveFlightIDs(ids ...string) *AircraftUpdateOne {
	_u.mutation.RemoveFlightIDs(ids...)
	return _u
}

// RemoveFlights removes "flights" edges to Flight entities.
func (_u *AircraftUpdateOne) RemoveFlights(v ...*Flight) *AircraftUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlightIDs(ids...)
}

// Where appends a list predicates to the AircraftUpdate builder.
func (_u *AircraftUpdateOne) Where(ps ...predicate.Aircraft) *AircraftUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AircraftUpdateOne) Select(field string, fields ...string) *AircraftUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Aircraft entity.
func (_u *AircraftUpdateOne) Save(ctx context.Context) (*Aircraft, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AircraftUpdateOne) SaveX(ctx context.Context) *Aircraft {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AircraftUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AircraftUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AircraftUpdateOne) sqlSave(ctx context.Context) (_node *Aircraft, err error) {
	_spec := sqlgraph.NewUpdateSpec(aircraft.Table, aircraft.Columns, sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Aircraft.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aircraft.FieldID)
		for _, f := range fields {
			if !aircraft.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aircraft.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Seats(); ok {
		_spec.SetField(aircraft.FieldSeats, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSeats(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, aircraft.FieldSeats, value)
		})
	}
	if _u.mutation.FlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlightsIDs(); len(nodes) > 0 && !_u.mutation.FlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Aircraft{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aircraft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
