// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/aircraft"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
)

// AircraftCreate is the builder for creating a Aircraft entity.
type AircraftCreate struct {
	config
	mutation *AircraftMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSeats sets the "seats" field.
func (_c *AircraftCreate) SetSeats(v []string) *AircraftCreate {
	_c.mutation.SetSeats(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AircraftCreate) SetID(v string) *AircraftCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddFlightIDs adds the "flights" edge to the Flight entity by IDs.
func (_c *AircraftCreate) AddFlightIDs(ids ...string) *AircraftCreate {
	_c.mutation.AddFlightIDs(ids...)
	return _c
}

// AddFlights adds the "flights" edges to the Flight entity.
func (_c *AircraftCreate) AddFlights(v ...*Flight) *AircraftCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFlightIDs(ids...)
}

// Mutation returns the AircraftMutation object of the builder.
func (_c *AircraftCreate) Mutation() *AircraftMutation {
	return _c.mutation
}

// Save creates the Aircraft in the database.
func (_c *AircraftCreate) Save(ctx context.Context) (*Aircraft, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AircraftCreate) SaveX(ctx context.Context) *Aircraft {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AircraftCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AircraftCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AircraftCreate) check() error {
	if _, ok := _c.mutation.Seats(); !ok {
		return &ValidationError{Name: "seats", err: errors.New(`ent: missing required field "Aircraft.seats"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := aircraft.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Aircraft.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AircraftCreate) sqlSave(ctx context.Context) (*Aircraft, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Aircraft.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AircraftCreate) createSpec() (*Aircraft, *sqlgraph.CreateSpec) {
	var (
		_node = &Aircraft{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aircraft.Table, sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Seats(); ok {
		_spec.SetField(aircraft.FieldSeats, field.TypeJSON, value)
		_node.Seats = value
	}
	if nodes := _c.mutation.FlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Aircraft.Create().
//		SetSeats(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AircraftUpsert) {
//			SetSeats(v+v).
//		}).
//		Exec(ctx)
func (_c *AircraftCreate) OnConflict(opts ...sql.ConflictOption) *AircraftUpsertOne {
	_c.conflict = opts
	return &AircraftUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Aircraft.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AircraftCreate) OnConflictColumns(columns ...string) *AircraftUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AircraftUpsertOne{
		create: _c,
	}
}

type (
	// AircraftUpsertOne is the builder for "upsert"-ing
	//  one Aircraft node.
	AircraftUpsertOne struct {
		create *AircraftCreate
	}

	// AircraftUpsert is the "OnConflict" setter.
	AircraftUpsert struct {
		*sql.UpdateSet
	}
)

// SetSeats sets the "seats" field.
func (u *AircraftUpsert) SetSeats(v []string) *AircraftUpsert {
	u.Set(aircraft.FieldSeats, v)
	return u
}

// UpdateSeats sets the "seats" field to the value that was provided on create.
func (u *AircraftUpsert) UpdateSeats() *AircraftUpsert {
	u.SetExcluded(aircraft.FieldSeats)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Aircraft.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aircraft.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AircraftUpsertOne) UpdateNewValues() *AircraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(aircraft.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Aircraft.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AircraftUpsertOne) Ignore() *AircraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AircraftUpsertOne) DoNothing() *AircraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AircraftCreate.OnConflict
// documentation for more info.
func (u *AircraftUpsertOne) Update(set func(*AircraftUpsert)) *AircraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AircraftUpsert{UpdateSet: update})
	}))
	return u
}

// SetSeats sets the "seats" field.
func (u *AircraftUpsertOne) SetSeats(v []string) *AircraftUpsertOne {
	return u.Update(func(s *AircraftUpsert) {
		s.SetSeats(v)
	})
}

// UpdateSeats sets the "seats" field to the value that was provided on create.
func (u *AircraftUpsertOne) UpdateSeats() *AircraftUpsertOne {
	return u.Update(func(s *AircraftUpsert) {
		s.UpdateSeats()
	})
}

// Exec executes the query.
func (u *AircraftUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AircraftCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AircraftUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AircraftUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AircraftUpsertOne.ID is not supported by MySQL driver. Use AircraftUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AircraftUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AircraftCreateBulk is the builder for creating many Aircraft entities in bulk.
type AircraftCreateBulk struct {
	config
	err      error
	builders []*AircraftCreate
	conflict []sql.ConflictOption
}

// Save creates the Aircraft entities in the database.
func (_c *AircraftCreateBulk) Save(ctx context.Context) ([]*Aircraft, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Aircraft, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AircraftMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AircraftCreateBulk) SaveX(ctx context.Context) []*Aircraft {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AircraftCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AircraftCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Aircraft.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AircraftUpsert) {
//			SetSeats(v+v).
//		}).
//		Exec(ctx)
func (_c *AircraftCreateBulk) OnConflict(opts ...sql.ConflictOption) *AircraftUpsertBulk {
	_c.conflict = opts
	return &AircraftUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Aircraft.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AircraftCreateBulk) OnConflictColumns(columns ...string) *AircraftUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AircraftUpsertBulk{
		create: _c,
	}
}

// AircraftUpsertBulk is the builder for "upsert"-ing
// a bulk of Aircraft nodes.
type AircraftUpsertBulk struct {
	create *AircraftCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Aircraft.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aircraft.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AircraftUpsertBulk) UpdateNewValues() *AircraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(aircraft.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Aircraft.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AircraftUpsertBulk) Ignore() *AircraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AircraftUpsertBulk) DoNothing() *AircraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AircraftCreateBulk.OnConflict
// documentation for more info.
func (u *AircraftUpsertBulk) Update(set func(*AircraftUpsert)) *AircraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AircraftUpsert{UpdateSet: update})
	}))
	return u
}

// SetSeats sets the "seats" field.
func (u *AircraftUpsertBulk) SetSeats(v []string) *AircraftUpsertBulk {
	return u.Update(func(s *AircraftUpsert) {
		s.SetSeats(v)
	})
}

// UpdateSeats sets the "seats" field to the value that was provided on create.
func (u *AircraftUpsertBulk) UpdateSeats() *AircraftUpsertBulk {
	return u.Update(func(s *AircraftUpsert) {
		s.UpdateSeats()
	})
}

// Exec executes the query.
func (u *AircraftUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AircraftCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AircraftCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AircraftUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
