// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/aircraft"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flightseat"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/ticket"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Aircraft is the client for interacting with the Aircraft builders.
	Aircraft *AircraftClient
	// Flight is the client for interacting with the Flight builders.
	Flight *FlightClient
	// FlightSeat is the client for interacting with the FlightSeat builders.
	FlightSeat *FlightSeatClient
	// Ticket is the client for interacting with the Ticket builders.
	Ticket *TicketClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Aircraft = NewAircraftClient(c.config)
	c.Flight = NewFlightClient(c.config)
	c.FlightSeat = NewFlightSeatClient(c.config)
	c.Ticket = NewTicketClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Aircraft:   NewAircraftClient(cfg),
		Flight:     NewFlightClient(cfg),
		FlightSeat: NewFlightSeatClient(cfg),
		Ticket:     NewTicketClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Aircraft:   NewAircraftClient(cfg),
		Flight:     NewFlightClient(cfg),
		FlightSeat: NewFlightSeatClient(cfg),
		Ticket:     NewTicketClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Aircraft.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Aircraft.Use(hooks...)
	c.Flight.Use(hooks...)
	c.FlightSeat.Use(hooks...)
	c.Ticket.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Aircraft.Intercept(interceptors...)
	c.Flight.Intercept(interceptors...)
	c.FlightSeat.Intercept(interceptors...)
	c.Ticket.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AircraftMutation:
		return c.Aircraft.mutate(ctx, m)
	case *FlightMutation:
		return c.Flight.mutate(ctx, m)
	case *FlightSeatMutation:
		return c.FlightSeat.mutate(ctx, m)
	case *TicketMutation:
		return c.Ticket.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AircraftClient is a client for the Aircraft schema.
type AircraftClient struct {
	config
}

// NewAircraftClient returns a client for the Aircraft from the given config.
func NewAircraftClient(c config) *AircraftClient {
	return &AircraftClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `aircraft.Hooks(f(g(h())))`.
func (c *AircraftClient) Use(hooks ...Hook) {
	c.hooks.Aircraft = append(c.hooks.Aircraft, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `aircraft.Intercept(f(g(h())))`.
func (c *AircraftClient) Intercept(interceptors ...Interceptor) {
	c.inters.Aircraft = append(c.inters.Aircraft, interceptors...)
}

// Create returns a builder for creating a Aircraft entity.
func (c *AircraftClient) Create() *AircraftCreate {
	mutation := newAircraftMutation(c.config, OpCreate)
	return &AircraftCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Aircraft entities.
func (c *AircraftClient) CreateBulk(builders ...*AircraftCreate) *AircraftCreateBulk {
	return &AircraftCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AircraftClient) MapCreateBulk(slice any, setFunc func(*AircraftCreate, int)) *AircraftCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AircraftCreateBulk{err: fmt.Errorf("calling to AircraftClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AircraftCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AircraftCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Aircraft.
func (c *AircraftClient) Update() *AircraftUpdate {
	mutation := newAircraftMutation(c.config, OpUpdate)
	return &AircraftUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AircraftClient) UpdateOne(_m *Aircraft) *AircraftUpdateOne {
	mutation := newAircraftMutation(c.config, OpUpdateOne, withAircraft(_m))
	return &AircraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AircraftClient) UpdateOneID(id string) *AircraftUpdateOne {
	mutation := newAircraftMutation(c.config, OpUpdateOne, withAircraftID(id))
	return &AircraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Aircraft.
func (c *AircraftClient) Delete() *AircraftDelete {
	mutation := newAircraftMutation(c.config, OpDelete)
	return &AircraftDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AircraftClient) DeleteOne(_m *Aircraft) *AircraftDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AircraftClient) DeleteOneID(id string) *AircraftDeleteOne {
	builder := c.Delete().Where(aircraft.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AircraftDeleteOne{builder}
}

// Query returns a query builder for Aircraft.
func (c *AircraftClient) Query() *AircraftQuery {
	return &AircraftQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAircraft},
		inters: c.Interceptors(),
	}
}

// Get returns a Aircraft entity by its id.
func (c *AircraftClient) Get(ctx context.Context, id string) (*Aircraft, error) {
	return c.Query().Where(aircraft.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AircraftClient) GetX(ctx context.Context, id string) *Aircraft {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFlights queries the flights edge of a Aircraft.
func (c *AircraftClient) QueryFlights(_m *Aircraft) *FlightQuery {
	query := (&FlightClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(aircraft.Table, aircraft.FieldID, id),
			sqlgraph.To(flight.Table, flight.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, aircraft.FlightsTable, aircraft.FlightsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AircraftClient) Hooks() []Hook {
	return c.hooks.Aircraft
}

// Interceptors returns the client interceptors.
func (c *AircraftClient) Interceptors() []Interceptor {
	return c.inters.Aircraft
}

func (c *AircraftClient) mutate(ctx context.Context, m *AircraftMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AircraftCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AircraftUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AircraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AircraftDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Aircraft mutation op: %q", m.Op())
	}
}

// FlightClient is a client for the Flight schema.
type FlightClient struct {
	config
}

// NewFlightClient returns a client for the Flight from the given config.
func NewFlightClient(c config) *FlightClient {
	return &FlightClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `flight.Hooks(f(g(h())))`.
func (c *FlightClient) Use(hooks ...Hook) {
	c.hooks.Flight = append(c.hooks.Flight, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `flight.Intercept(f(g(h())))`.
func (c *FlightClient) Intercept(interceptors ...Interceptor) {
	c.inters.Flight = append(c.inters.Flight, interceptors...)
}

// Create returns a builder for creating a Flight entity.
func (c *FlightClient) Create() *FlightCreate {
	mutation := newFlightMutation(c.config, OpCreate)
	return &FlightCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Flight entities.
func (c *FlightClient) CreateBulk(builders ...*FlightCreate) *FlightCreateBulk {
	return &FlightCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FlightClient) MapCreateBulk(slice any, setFunc func(*FlightCreate, int)) *FlightCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FlightCreateBulk{err: fmt.Errorf("calling to FlightClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FlightCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FlightCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Flight.
func (c *FlightClient) Update() *FlightUpdate {
	mutation := newFlightMutation(c.config, OpUpdate)
	return &FlightUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FlightClient) UpdateOne(_m *Flight) *FlightUpdateOne {
	mutation := newFlightMutation(c.config, OpUpdateOne, withFlight(_m))
	return &FlightUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FlightClient) UpdateOneID(id string) *FlightUpdateOne {
	mutation := newFlightMutation(c.config, OpUpdateOne, withFlightID(id))
	return &FlightUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Flight.
func (c *FlightClient) Delete() *FlightDelete {
	mutation := newFlightMutation(c.config, OpDelete)
	return &FlightDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FlightClient) DeleteOne(_m *Flight) *FlightDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FlightClient) DeleteOneID(id string) *FlightDeleteOne {
	builder := c.Delete().Where(flight.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FlightDeleteOne{builder}
}

// Query returns a query builder for Flight.
func (c *FlightClient) Query() *FlightQuery {
	return &FlightQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFlight},
		inters: c.Interceptors(),
	}
}

// Get returns a Flight entity by its id.
func (c *FlightClient) Get(ctx context.Context, id string) (*Flight, error) {
	return c.Query().Where(flight.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FlightClient) GetX(ctx context.Context, id string) *Flight {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAircraft queries the aircraft edge of a Flight.
func (c *FlightClient) QueryAircraft(_m *Flight) *AircraftQuery {
	query := (&AircraftClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(flight.Table, flight.FieldID, id),
			sqlgraph.To(aircraft.Table, aircraft.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flight.AircraftTable, flight.AircraftColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySeats queries the seats edge of a Flight.
func (c *FlightClient) QuerySeats(_m *Flight) *FlightSeatQuery {
	query := (&FlightSeatClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(flight.Table, flight.FieldID, id),
			sqlgraph.To(flightseat.Table, flightseat.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, flight.SeatsTable, flight.SeatsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTickets queries the tickets edge of a Flight.
func (c *FlightClient) QueryTickets(_m *Flight) *TicketQuery {
	query := (&TicketClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(flight.Table, flight.FieldID, id),
			sqlgraph.To(ticket.Table, ticket.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, flight.TicketsTable, flight.TicketsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FlightClient) Hooks() []Hook {
	return c.hooks.Flight
}

// Interceptors returns the client interceptors.
func (c *FlightClient) Interceptors() []Interceptor {
	return c.inters.Flight
}

func (c *FlightClient) mutate(ctx context.Context, m *FlightMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FlightCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FlightUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FlightUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FlightDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Flight mutation op: %q", m.Op())
	}
}

// FlightSeatClient is a client for the FlightSeat schema.
type FlightSeatClient struct {
	config
}

// NewFlightSeatClient returns a client for the FlightSeat from the given config.
func NewFlightSeatClient(c config) *FlightSeatClient {
	return &FlightSeatClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `flightseat.Hooks(f(g(h())))`.
func (c *FlightSeatClient) Use(hooks ...Hook) {
	c.hooks.FlightSeat = append(c.hooks.FlightSeat, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `flightseat.Intercept(f(g(h())))`.
func (c *FlightSeatClient) Intercept(interceptors ...Interceptor) {
	c.inters.FlightSeat = append(c.inters.FlightSeat, interceptors...)
}

// Create returns a builder for creating a FlightSeat entity.
func (c *FlightSeatClient) Create() *FlightSeatCreate {
	mutation := newFlightSeatMutation(c.config, OpCreate)
	return &FlightSeatCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FlightSeat entities.
func (c *FlightSeatClient) CreateBulk(builders ...*FlightSeatCreate) *FlightSeatCreateBulk {
	return &FlightSeatCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FlightSeatClient) MapCreateBulk(slice any, setFunc func(*FlightSeatCreate, int)) *FlightSeatCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FlightSeatCreateBulk{err: fmt.Errorf("calling to FlightSeatClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FlightSeatCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FlightSeatCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FlightSeat.
func (c *FlightSeatClient) Update() *FlightSeatUpdate {
	mutation := newFlightSeatMutation(c.config, OpUpdate)
	return &FlightSeatUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FlightSeatClient) UpdateOne(_m *FlightSeat) *FlightSeatUpdateOne {
	mutation := newFlightSeatMutation(c.config, OpUpdateOne, withFlightSeat(_m))
	return &FlightSeatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FlightSeatClient) UpdateOneID(id int) *FlightSeatUpdateOne {
	mutation := newFlightSeatMutation(c.config, OpUpdateOne, withFlightSeatID(id))
	return &FlightSeatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FlightSeat.
func (c *FlightSeatClient) Delete() *FlightSeatDelete {
	mutation := newFlightSeatMutation(c.config, OpDelete)
	return &FlightSeatDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FlightSeatClient) DeleteOne(_m *FlightSeat) *FlightSeatDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FlightSeatClient) DeleteOneID(id int) *FlightSeatDeleteOne {
	builder := c.Delete().Where(flightseat.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FlightSeatDeleteOne{builder}
}

// Query returns a query builder for FlightSeat.
func (c *FlightSeatClient) Query() *FlightSeatQuery {
	return &FlightSeatQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFlightSeat},
		inters: c.Interceptors(),
	}
}

// Get returns a FlightSeat entity by its id.
func (c *FlightSeatClient) Get(ctx context.Context, id int) (*FlightSeat, error) {
	return c.Query().Where(flightseat.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FlightSeatClient) GetX(ctx context.Context, id int) *FlightSeat {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFlight queries the flight edge of a FlightSeat.
func (c *FlightSeatClient) QueryFlight(_m *FlightSeat) *FlightQuery {
	query := (&FlightClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(flightseat.Table, flightseat.FieldID, id),
			sqlgraph.To(flight.Table, flight.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flightseat.FlightTable, flightseat.FlightColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FlightSeatClient) Hooks() []Hook {
	return c.hooks.FlightSeat
}

// Interceptors returns the client interceptors.
func (c *FlightSeatClient) Interceptors() []Interceptor {
	return c.inters.FlightSeat
}

func (c *FlightSeatClient) mutate(ctx context.Context, m *FlightSeatMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FlightSeatCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FlightSeatUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FlightSeatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FlightSeatDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FlightSeat mutation op: %q", m.Op())
	}
}

// TicketClient is a client for the Ticket schema.
type TicketClient struct {
	config
}

// NewTicketClient returns a client for the Ticket from the given config.
func NewTicketClient(c config) *TicketClient {
	return &TicketClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ticket.Hooks(f(g(h())))`.
func (c *TicketClient) Use(hooks ...Hook) {
	c.hooks.Ticket = append(c.hooks.Ticket, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ticket.Intercept(f(g(h())))`.
func (c *TicketClient) Intercept(interceptors ...Interceptor) {
	c.inters.Ticket = append(c.inters.Ticket, interceptors...)
}

// Create returns a builder for creating a Ticket entity.
func (c *TicketClient) Create() *TicketCreate {
	mutation := newTicketMutation(c.config, OpCreate)
	return &TicketCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Ticket entities.
func (c *TicketClient) CreateBulk(builders ...*TicketCreate) *TicketCreateBulk {
	return &TicketCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TicketClient) MapCreateBulk(slice any, setFunc func(*TicketCreate, int)) *TicketCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TicketCreateBulk{err: fmt.Errorf("calling to TicketClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TicketCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TicketCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Ticket.
func (c *TicketClient) Update() *TicketUpdate {
	mutation := newTicketMutation(c.config, OpUpdate)
	return &TicketUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TicketClient) UpdateOne(_m *Ticket) *TicketUpdateOne {
	mutation := newTicketMutation(c.config, OpUpdateOne, withTicket(_m))
	return &TicketUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TicketClient) UpdateOneID(id string) *TicketUpdateOne {
	mutation := newTicketMutation(c.config, OpUpdateOne, withTicketID(id))
	return &TicketUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Ticket.
func (c *TicketClient) Delete() *TicketDelete {
	mutation := newTicketMutation(c.config, OpDelete)
	return &TicketDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TicketClient) DeleteOne(_m *Ticket) *TicketDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TicketClient) DeleteOneID(id string) *TicketDeleteOne {
	builder := c.Delete().Where(ticket.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TicketDeleteOne{builder}
}

// Query returns a query builder for Ticket.
func (c *TicketClient) Query() *TicketQuery {
	return &TicketQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTicket},
		inters: c.Interceptors(),
	}
}

// Get returns a Ticket entity by its id.
func (c *TicketClient) Get(ctx context.Context, id string) (*Ticket, error) {
	return c.Query().Where(ticket.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TicketClient) GetX(ctx context.Context, id string) *Ticket {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFlight queries the flight edge of a Ticket.
func (c *TicketClient) QueryFlight(_m *Ticket) *FlightQuery {
	query := (&FlightClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ticket.Table, ticket.FieldID, id),
			sqlgraph.To(flight.Table, flight.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ticket.FlightTable, ticket.FlightColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TicketClient) Hooks() []Hook {
	return c.hooks.Ticket
}

// Interceptors returns the client interceptors.
func (c *TicketClient) Interceptors() []Interceptor {
	return c.inters.Ticket
}

func (c *TicketClient) mutate(ctx context.Context, m *TicketMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TicketCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TicketUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TicketUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TicketDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Ticket mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Aircraft, Flight, FlightSeat, Ticket []ent.Hook
	}
	inters struct {
		Aircraft, Flight, FlightSeat, Ticket []ent.Interceptor
	}
)
