// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/aircraft"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flightseat"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/ticket"
)

// FlightUpdate is the builder for updating Flight entities.
type FlightUpdate struct {
	config
	hooks    []Hook
	mutation *FlightMutation
}

// Where appends a list predicates to the FlightUpdate builder.
func (_u *FlightUpdate) Where(ps ...predicate.Flight) *FlightUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *FlightUpdate) SetOrigin(v string) *FlightUpdate {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableOrigin(v *string) *FlightUpdate {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *FlightUpdate) SetDestination(v string) *FlightUpdate {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableDestination(v *string) *FlightUpdate {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetScheduledDeparture sets the "scheduled_departure" field.
func (_u *FlightUpdate) SetScheduledDeparture(v time.Time) *FlightUpdate {
	_u.mutation.SetScheduledDeparture(v)
	return _u
}

// SetNillableScheduledDeparture sets the "scheduled_departure" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableScheduledDeparture(v *time.Time) *FlightUpdate {
	if v != nil {
		_u.SetScheduledDeparture(*v)
	}
	return _u
}

// SetScheduledArrival sets the "scheduled_arrival" field.
func (_u *FlightUpdate) SetScheduledArrival(v time.Time) *FlightUpdate {
	_u.mutation.SetScheduledArrival(v)
	return _u
}

// SetNillableScheduledArrival sets the "scheduled_arrival" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableScheduledArrival(v *time.Time) *FlightUpdate {
	if v != nil {
		_u.SetScheduledArrival(*v)
	}
	return _u
}

// SetCloseBookingBufferNs sets the "close_booking_buffer_ns" field.
func (_u *FlightUpdate) SetCloseBookingBufferNs(v int64) *FlightUpdate {
	_u.mutation.ResetCloseBookingBufferNs()
	_u.mutation.SetCloseBookingBufferNs(v)
	return _u
}

// SetNillableCloseBookingBufferNs sets the "close_booking_buffer_ns" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableCloseBookingBufferNs(v *int64) *FlightUpdate {
	if v != nil {
		_u.SetCloseBookingBufferNs(*v)
	}
	return _u
}

// AddCloseBookingBufferNs adds value to the "close_booking_buffer_ns" field.
func (_u *FlightUpdate) AddCloseBookingBufferNs(v int64) *FlightUpdate {
	_u.mutation.AddCloseBookingBufferNs(v)
	return _u
}

// SetAircraftID sets the "aircraft" edge to the Aircraft entity by ID.
func (_u *FlightUpdate) SetAircraftID(id string) *FlightUpdate {
	_u.mutation.SetAircraftID(id)
	return _u
}

// SetAircraft sets the "aircraft" edge to the Aircraft entity.
func (_u *FlightUpdate) SetAircraft(v *Aircraft) *FlightUpdate {
	return _u.SetAircraftID(v.ID)
}

// AddSeatIDs adds the "seats" edge to the FlightSeat entity by IDs.
func (_u *FlightUpdate) AddSeatIDs(ids ...int) *FlightUpdate {
	_u.mutation.AddSeatIDs(ids...)
	return _u
}

// AddSeats adds the "seats" edges to the FlightSeat entity.
func (_u *FlightUpdate) AddSeats(v ...*FlightSeat) *FlightUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeatIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_u *FlightUpdate) AddTicketIDs(ids ...string) *FlightUpdate {
	_u.mutation.AddTicketIDs(ids...)
	return _u
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_u *FlightUpdate) AddTickets(v ...*Ticket) *FlightUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTicketIDs(ids...)
}

// Mutation returns the FlightMutation object of the builder.
func (_u *FlightUpdate) Mutation() *FlightMutation {
	return _u.mutation
}

// ClearAircraft clears the "aircraft" edge to the Aircraft entity.
func (_u *FlightUpdate) ClearAircraft() *FlightUpdate {
	_u.mutation.ClearAircraft()
	return _u
}

// ClearSeats clears all "seats" edges to the FlightSeat entity.
func (_u *FlightUpdate) ClearSeats() *FlightUpdate {
	_u.mutation.ClearSeats()
	return _u
}

// RemoveSeatIDs removes the "seats" edge to FlightSeat entities by IDs.
func (_u *FlightUpdate) RemoveSeatIDs(ids ...int) *FlightUpdate {
	_u.mutation.RemoveSeatIDs(ids...)
	return _u
}

// RemoveSeats removes "seats" edges to FlightSeat entities.
func (_u *FlightUpdate) RemoveSeats(v ...*FlightSeat) *FlightUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeatIDs(ids...)
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (_u *FlightUpdate) ClearTickets() *FlightUpdate {
	_u.mutation.ClearTickets()
	return _u
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (_u *FlightUpdate) RemoveTicketIDs(ids ...string) *FlightUpdate {
	_u.mutation.RemoveTicketIDs(ids...)
	return _u
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (_u *FlightUpdate) RemoveTickets(v ...*Ticket) *FlightUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTicketIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlightUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlightUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlightUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlightUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlightUpdate) check() error {
	if v, ok := _u.mutation.Origin(); ok {
		if err := flight.OriginValidator(v); err != nil {
			return &ValidationError{Name: "origin", err: fmt.Errorf(`ent: validator failed for field "Flight.origin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Destination(); ok {
		if err := flight.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Flight.destination": %w`, err)}
		}
	}
	if _u.mutation.AircraftCleared() && len(_u.mutation.AircraftIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flight.aircraft"`)
	}
	return nil
}

func (_u *FlightUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(flight.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(flight.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduledDeparture(); ok {
		_spec.SetField(flight.FieldScheduledDeparture, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScheduledArrival(); ok {
		_spec.SetField(flight.FieldScheduledArrival, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CloseBookingBufferNs(); ok {
		_spec.SetField(flight.FieldCloseBookingBufferNs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCloseBookingBufferNs(); ok {
		_spec.AddField(flight.FieldCloseBookingBufferNs, field.TypeInt64, value)
	}
	if _u.mutation.AircraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AircraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeatsIDs(); len(nodes) > 0 && !_u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.TicketsTable,
			Columns: []string{flight.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !_u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.TicketsTable,
			Columns: []string{flight.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.TicketsTable,
			Columns: []string{flight.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlightUpdateOne is the builder for updating a single Flight entity.
type FlightUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightMutation
}

// SetOrigin sets the "origin" field.
func (_u *FlightUpdateOne) SetOrigin(v string) *FlightUpdateOne {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableOrigin(v *string) *FlightUpdateOne {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *FlightUpdateOne) SetDestination(v string) *FlightUpdateOne {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableDestination(v *string) *FlightUpdateOne {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetScheduledDeparture sets the "scheduled_departure" field.
func (_u *FlightUpdateOne) SetScheduledDeparture(v time.Time) *FlightUpdateOne {
	_u.mutation.SetScheduledDeparture(v)
	return _u
}

// SetNillableScheduledDeparture sets the "scheduled_departure" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableScheduledDeparture(v *time.Time) *FlightUpdateOne {
	if v != nil {
		_u.SetScheduledDeparture(*v)
	}
	return _u
}

// SetScheduledArrival sets the "scheduled_arrival" field.
func (_u *FlightUpdateOne) SetScheduledArrival(v time.Time) *FlightUpdateOne {
	_u.mutation.SetScheduledArrival(v)
	return _u
}

// SetNillableScheduledArrival sets the "scheduled_arrival" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableScheduledArrival(v *time.Time) *FlightUpdateOne {
	if v != nil {
		_u.SetScheduledArrival(*v)
	}
	return _u
}

// SetCloseBookingBufferNs sets the "close_booking_buffer_ns" field.
func (_u *FlightUpdateOne) SetCloseBookingBufferNs(v int64) *FlightUpdateOne {
	_u.mutation.ResetCloseBookingBufferNs()
	_u.mutation.SetCloseBookingBufferNs(v)
	return _u
}

// SetNillableCloseBookingBufferNs sets the "close_booking_buffer_ns" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableCloseBookingBufferNs(v *int64) *FlightUpdateOne {
	if v != nil {
		_u.SetCloseBookingBufferNs(*v)
	}
	return _u
}

// AddCloseBookingBufferNs adds value to the "close_booking_buffer_ns" field.
func (_u *FlightUpdateOne) AddCloseBookingBufferNs(v int64) *FlightUpdateOne {
	_u.mutation.AddCloseBookingBufferNs(v)
	return _u
}

// SetAircraftID sets the "aircraft" edge to the Aircraft entity by ID.
func (_u *FlightUpdateOne) SetAircraftID(id string) *FlightUpdateOne {
	_u.mutation.SetAircraftID(id)
	return _u
}

// SetAircraft sets the "aircraft" edge to the Aircraft entity.
func (_u *FlightUpdateOne) SetAircraft(v *Aircraft) *FlightUpdateOne {
	return _u.SetAircraftID(v.ID)
}

// AddSeatIDs adds the "seats" edge to the FlightSeat entity by IDs.
func (_u *FlightUpdateOne) AddSeatIDs(ids ...int) *FlightUpdateOne {
	_u.mutation.AddSeatIDs(ids...)
	return _u
}

// AddSeats adds the "seats" edges to the FlightSeat entity.
func (_u *FlightUpdateOne) AddSeats(v ...*FlightSeat) *FlightUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeatIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_u *FlightUpdateOne) AddTicketIDs(ids ...string) *FlightUpdateOne {
	_u.mutation.AddTicketIDs(ids...)
	return _u
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_u *FlightUpdateOne) AddTickets(v ...*Ticket) *FlightUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTicketIDs(ids...)
}

// Mutation returns the FlightMutation object of the builder.
func (_u *FlightUpdateOne) Mutation() *FlightMutation {
	return _u.mutation
}

// ClearAircraft clears the "aircraft" edge to the Aircraft entity.
func (_u *FlightUpdateOne) ClearAircraft() *FlightUpdateOne {
	_u.mutation.ClearAircraft()
	return _u
}

// ClearSeats clears all "seats" edges to the FlightSeat entity.
func (_u *FlightUpdateOne) ClearSeats() *FlightUpdateOne {
	_u.mutation.ClearSeats()
	return _u
}

// RemoveSeatIDs removes the "seats" edge to FlightSeat entities by IDs.
func (_u *FlightUpdateOne) RemoveSeatIDs(ids ...int) *FlightUpdateOne {
	_u.mutation.RemoveSeatIDs(ids...)
	return _u
}

// RemoveSeats removes "seats" edges to FlightSeat entities.
func (_u *FlightUpdateOne) RemoveSeats(v ...*FlightSeat) *FlightUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeatIDs(ids...)
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (_u *FlightUpdateOne) ClearTickets() *FlightUpdateOne {
	_u.mutation.ClearTickets()
	return _u
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (_u *FlightUpdateOne) RemoveTicketIDs(ids ...string) *FlightUpdateOne {
	_u.mutation.RemoveTicketIDs(ids...)
	return _u
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (_u *FlightUpdateOne) RemoveTickets(v ...*Ticket) *FlightUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTicketIDs(ids...)
}

// Where appends a list predicates to the FlightUpdate builder.
func (_u *FlightUpdateOne) Where(ps ...predicate.Flight) *FlightUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlightUpdateOne) Select(field string, fields ...string) *FlightUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Flight entity.
func (_u *FlightUpdateOne) Save(ctx context.Context) (*Flight, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlightUpdateOne) SaveX(ctx context.Context) *Flight {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlightUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlightUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlightUpdateOne) check() error {
	if v, ok := _u.mutation.Origin(); ok {
		if err := flight.OriginValidator(v); err != nil {
			return &ValidationError{Name: "origin", err: fmt.Errorf(`ent: validator failed for field "Flight.origin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Destination(); ok {
		if err := flight.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Flight.destination": %w`, err)}
		}
	}
	if _u.mutation.AircraftCleared() && len(_u.mutation.AircraftIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flight.aircraft"`)
	}
	return nil
}

func (_u *FlightUpdateOne) sqlSave(ctx context.Context) (_node *Flight, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flight.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flight.FieldID)
		for _, f := range fields {
			if !flight.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(flight.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(flight.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduledDeparture(); ok {
		_spec.SetField(flight.FieldScheduledDeparture, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScheduledArrival(); ok {
		_spec.SetField(flight.FieldScheduledArrival, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CloseBookingBufferNs(); ok {
		_spec.SetField(flight.FieldCloseBookingBufferNs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCloseBookingBufferNs(); ok {
		_spec.AddField(flight.FieldCloseBookingBufferNs, field.TypeInt64, value)
	}
	if _u.mutation.AircraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AircraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeatsIDs(); len(nodes) > 0 && !_u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.TicketsTable,
			Columns: []string{flight.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !_u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.TicketsTable,
			Columns: []string{flight.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.TicketsTable,
			Columns: []string{flight.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Flight{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
