// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/aircraft"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flightseat"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/ticket"
)

// FlightCreate is the builder for creating a Flight entity.
type FlightCreate struct {
	config
	mutation *FlightMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrigin sets the "origin" field.
func (_c *FlightCreate) SetOrigin(v string) *FlightCreate {
	_c.mutation.SetOrigin(v)
	return _c
}

// SetDestination sets the "destination" field.
func (_c *FlightCreate) SetDestination(v string) *FlightCreate {
	_c.mutation.SetDestination(v)
	return _c
}

// SetScheduledDeparture sets the "scheduled_departure" field.
func (_c *FlightCreate) SetScheduledDeparture(v time.Time) *FlightCreate {
	_c.mutation.SetScheduledDeparture(v)
	return _c
}

// SetScheduledArrival sets the "scheduled_arrival" field.
func (_c *FlightCreate) SetScheduledArrival(v time.Time) *FlightCreate {
	_c.mutation.SetScheduledArrival(v)
	return _c
}

// SetCloseBookingBufferNs sets the "close_booking_buffer_ns" field.
func (_c *FlightCreate) SetCloseBookingBufferNs(v int64) *FlightCreate {
	_c.mutation.SetCloseBookingBufferNs(v)
	return _c
}

// SetID sets the "id" field.
func (_c *FlightCreate) SetID(v string) *FlightCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetAircraftID sets the "aircraft" edge to the Aircraft entity by ID.
func (_c *FlightCreate) SetAircraftID(id string) *FlightCreate {
	_c.mutation.SetAircraftID(id)
	return _c
}

// SetAircraft sets the "aircraft" edge to the Aircraft entity.
func (_c *FlightCreate) SetAircraft(v *Aircraft) *FlightCreate {
	return _c.SetAircraftID(v.ID)
}

// AddSeatIDs adds the "seats" edge to the FlightSeat entity by IDs.
func (_c *FlightCreate) AddSeatIDs(ids ...int) *FlightCreate {
	_c.mutation.AddSeatIDs(ids...)
	return _c
}

// AddSeats adds the "seats" edges to the FlightSeat entity.
func (_c *FlightCreate) AddSeats(v ...*FlightSeat) *FlightCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSeatIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_c *FlightCreate) AddTicketIDs(ids ...string) *FlightCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_c *FlightCreate) AddTickets(v ...*Ticket) *FlightCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// Mutation returns the FlightMutation object of the builder.
func (_c *FlightCreate) Mutation() *FlightMutation {
	return _c.mutation
}

// Save creates the Flight in the database.
func (_c *FlightCreate) Save(ctx context.Context) (*Flight, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FlightCreate) SaveX(ctx context.Context) *Flight {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlightCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlightCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FlightCreate) check() error {
	if _, ok := _c.mutation.Origin(); !ok {
		return &ValidationError{Name: "origin", err: errors.New(`ent: missing required field "Flight.origin"`)}
	}
	if v, ok := _c.mutation.Origin(); ok {
		if err := flight.OriginValidator(v); err != nil {
			return &ValidationError{Name: "origin", err: fmt.Errorf(`ent: validator failed for field "Flight.origin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Destination(); !ok {
		return &ValidationError{Name: "destination", err: errors.New(`ent: missing required field "Flight.destination"`)}
	}
	if v, ok := _c.mutation.Destination(); ok {
		if err := flight.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Flight.destination": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScheduledDeparture(); !ok {
		return &ValidationError{Name: "scheduled_departure", err: errors.New(`ent: missing required field "Flight.scheduled_departure"`)}
	}
	if _, ok := _c.mutation.ScheduledArrival(); !ok {
		return &ValidationError{Name: "scheduled_arrival", err: errors.New(`ent: missing required field "Flight.scheduled_arrival"`)}
	}
	if _, ok := _c.mutation.CloseBookingBufferNs(); !ok {
		return &ValidationError{Name: "close_booking_buffer_ns", err: errors.New(`ent: missing required field "Flight.close_booking_buffer_ns"`)}
	}
	if len(_c.mutation.AircraftIDs()) == 0 {
		return &ValidationError{Name: "aircraft", err: errors.New(`ent: missing required edge "Flight.aircraft"`)}
	}
	return nil
}

func (_c *FlightCreate) sqlSave(ctx context.Context) (*Flight, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Flight.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FlightCreate) createSpec() (*Flight, *sqlgraph.CreateSpec) {
	var (
		_node = &Flight{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(flight.Table, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Origin(); ok {
		_spec.SetField(flight.FieldOrigin, field.TypeString, value)
		_node.Origin = value
	}
	if value, ok := _c.mutation.Destination(); ok {
		_spec.SetField(flight.FieldDestination, field.TypeString, value)
		_node.Destination = value
	}
	if value, ok := _c.mutation.ScheduledDeparture(); ok {
		_spec.SetField(flight.FieldScheduledDeparture, field.TypeTime, value)
		_node.ScheduledDeparture = value
	}
	if value, ok := _c.mutation.ScheduledArrival(); ok {
		_spec.SetField(flight.FieldScheduledArrival, field.TypeTime, value)
		_node.ScheduledArrival = value
	}
	if value, ok := _c.mutation.CloseBookingBufferNs(); ok {
		_spec.SetField(flight.FieldCloseBookingBufferNs, field.TypeInt64, value)
		_node.CloseBookingBufferNs = value
	}
	if nodes := _c.mutation.AircraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.aircraft_flights = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.TicketsTable,
			Columns: []string{flight.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Flight.Create().
//		SetOrigin(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FlightUpsert) {
//			SetOrigin(v+v).
//		}).
//		Exec(ctx)
func (_c *FlightCreate) OnConflict(opts ...sql.ConflictOption) *FlightUpsertOne {
	_c.conflict = opts
	return &FlightUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Flight.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FlightCreate) OnConflictColumns(columns ...string) *FlightUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FlightUpsertOne{
		create: _c,
	}
}

type (
	// FlightUpsertOne is the builder for "upsert"-ing
	//  one Flight node.
	FlightUpsertOne struct {
		create *FlightCreate
	}

	// FlightUpsert is the "OnConflict" setter.
	FlightUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrigin sets the "origin" field.
func (u *FlightUpsert) SetOrigin(v string) *FlightUpsert {
	u.Set(flight.FieldOrigin, v)
	return u
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *FlightUpsert) UpdateOrigin() *FlightUpsert {
	u.SetExcluded(flight.FieldOrigin)
	return u
}

// SetDestination sets the "destination" field.
func (u *FlightUpsert) SetDestination(v string) *FlightUpsert {
	u.Set(flight.FieldDestination, v)
	return u
}

// UpdateDestination sets the "destination" field to the value that was provided on create.
func (u *FlightUpsert) UpdateDestination() *FlightUpsert {
	u.SetExcluded(flight.FieldDestination)
	return u
}

// SetScheduledDeparture sets the "scheduled_departure" field.
func (u *FlightUpsert) SetScheduledDeparture(v time.Time) *FlightUpsert {
	u.Set(flight.FieldScheduledDeparture, v)
	return u
}

// UpdateScheduledDeparture sets the "scheduled_departure" field to the value that was provided on create.
func (u *FlightUpsert) UpdateScheduledDeparture() *FlightUpsert {
	u.SetExcluded(flight.FieldScheduledDeparture)
	return u
}

// SetScheduledArrival sets the "scheduled_arrival" field.
func (u *FlightUpsert) SetScheduledArrival(v time.Time) *FlightUpsert {
	u.Set(flight.FieldScheduledArrival, v)
	return u
}

// UpdateScheduledArrival sets the "scheduled_arrival" field to the value that was provided on create.
func (u *FlightUpsert) UpdateScheduledArrival() *FlightUpsert {
	u.SetExcluded(flight.FieldScheduledArrival)
	return u
}

// SetCloseBookingBufferNs sets the "close_booking_buffer_ns" field.
func (u *FlightUpsert) SetCloseBookingBufferNs(v int64) *FlightUpsert {
	u.Set(flight.FieldCloseBookingBufferNs, v)
	return u
}

// UpdateCloseBookingBufferNs sets the "close_booking_buffer_ns" field to the value that was provided on create.
func (u *FlightUpsert) UpdateCloseBookingBufferNs() *FlightUpsert {
	u.SetExcluded(flight.FieldCloseBookingBufferNs)
	return u
}

// AddCloseBookingBufferNs adds v to the "close_booking_buffer_ns" field.
func (u *FlightUpsert) AddCloseBookingBufferNs(v int64) *FlightUpsert {
	u.Add(flight.FieldCloseBookingBufferNs, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Flight.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(flight.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FlightUpsertOne) UpdateNewValues() *FlightUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(flight.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Flight.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FlightUpsertOne) Ignore() *FlightUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FlightUpsertOne) DoNothing() *FlightUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FlightCreate.OnConflict
// documentation for more info.
func (u *FlightUpsertOne) Update(set func(*FlightUpsert)) *FlightUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FlightUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrigin sets the "origin" field.
func (u *FlightUpsertOne) SetOrigin(v string) *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.SetOrigin(v)
	})
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *FlightUpsertOne) UpdateOrigin() *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateOrigin()
	})
}

// SetDestination sets the "destination" field.
func (u *FlightUpsertOne) SetDestination(v string) *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.SetDestination(v)
	})
}

// UpdateDestination sets the "destination" field to the value that was provided on create.
func (u *FlightUpsertOne) UpdateDestination() *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateDestination()
	})
}

// SetScheduledDeparture sets the "scheduled_departure" field.
func (u *FlightUpsertOne) SetScheduledDeparture(v time.Time) *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.SetScheduledDeparture(v)
	})
}

// UpdateScheduledDeparture sets the "scheduled_departure" field to the value that was provided on create.
func (u *FlightUpsertOne) UpdateScheduledDeparture() *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateScheduledDeparture()
	})
}

// SetScheduledArrival sets the "scheduled_arrival" field.
func (u *FlightUpsertOne) SetScheduledArrival(v time.Time) *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.SetScheduledArrival(v)
	})
}

// UpdateScheduledArrival sets the "scheduled_arrival" field to the value that was provided on create.
func (u *FlightUpsertOne) UpdateScheduledArrival() *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateScheduledArrival()
	})
}

// SetCloseBookingBufferNs sets the "close_booking_buffer_ns" field.
func (u *FlightUpsertOne) SetCloseBookingBufferNs(v int64) *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.SetCloseBookingBufferNs(v)
	})
}

// AddCloseBookingBufferNs adds v to the "close_booking_buffer_ns" field.
func (u *FlightUpsertOne) AddCloseBookingBufferNs(v int64) *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.AddCloseBookingBufferNs(v)
	})
}

// UpdateCloseBookingBufferNs sets the "close_booking_buffer_ns" field to the value that was provided on create.
func (u *FlightUpsertOne) UpdateCloseBookingBufferNs() *FlightUpsertOne {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateCloseBookingBufferNs()
	})
}

// Exec executes the query.
func (u *FlightUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FlightCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FlightUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FlightUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: FlightUpsertOne.ID is not supported by MySQL driver. Use FlightUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FlightUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FlightCreateBulk is the builder for creating many Flight entities in bulk.
type FlightCreateBulk struct {
	config
	err      error
	builders []*FlightCreate
	conflict []sql.ConflictOption
}

// Save creates the Flight entities in the database.
func (_c *FlightCreateBulk) Save(ctx context.Context) ([]*Flight, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Flight, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlightMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FlightCreateBulk) SaveX(ctx context.Context) []*Flight {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlightCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlightCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Flight.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FlightUpsert) {
//			SetOrigin(v+v).
//		}).
//		Exec(ctx)
func (_c *FlightCreateBulk) OnConflict(opts ...sql.ConflictOption) *FlightUpsertBulk {
	_c.conflict = opts
	return &FlightUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Flight.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FlightCreateBulk) OnConflictColumns(columns ...string) *FlightUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FlightUpsertBulk{
		create: _c,
	}
}

// FlightUpsertBulk is the builder for "upsert"-ing
// a bulk of Flight nodes.
type FlightUpsertBulk struct {
	create *FlightCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Flight.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(flight.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FlightUpsertBulk) UpdateNewValues() *FlightUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(flight.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Flight.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FlightUpsertBulk) Ignore() *FlightUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FlightUpsertBulk) DoNothing() *FlightUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FlightCreateBulk.OnConflict
// documentation for more info.
func (u *FlightUpsertBulk) Update(set func(*FlightUpsert)) *FlightUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FlightUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrigin sets the "origin" field.
func (u *FlightUpsertBulk) SetOrigin(v string) *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.SetOrigin(v)
	})
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *FlightUpsertBulk) UpdateOrigin() *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateOrigin()
	})
}

// SetDestination sets the "destination" field.
func (u *FlightUpsertBulk) SetDestination(v string) *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.SetDestination(v)
	})
}

// UpdateDestination sets the "destination" field to the value that was provided on create.
func (u *FlightUpsertBulk) UpdateDestination() *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateDestination()
	})
}

// SetScheduledDeparture sets the "scheduled_departure" field.
func (u *FlightUpsertBulk) SetScheduledDeparture(v time.Time) *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.SetScheduledDeparture(v)
	})
}

// UpdateScheduledDeparture sets the "scheduled_departure" field to the value that was provided on create.
func (u *FlightUpsertBulk) UpdateScheduledDeparture() *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateScheduledDeparture()
	})
}

// SetScheduledArrival sets the "scheduled_arrival" field.
func (u *FlightUpsertBulk) SetScheduledArrival(v time.Time) *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.SetScheduledArrival(v)
	})
}

// UpdateScheduledArrival sets the "scheduled_arrival" field to the value that was provided on create.
func (u *FlightUpsertBulk) UpdateScheduledArrival() *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateScheduledArrival()
	})
}

// SetCloseBookingBufferNs sets the "close_booking_buffer_ns" field.
func (u *FlightUpsertBulk) SetCloseBookingBufferNs(v int64) *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.SetCloseBookingBufferNs(v)
	})
}

// AddCloseBookingBufferNs adds v to the "close_booking_buffer_ns" field.
func (u *FlightUpsertBulk) AddCloseBookingBufferNs(v int64) *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.AddCloseBookingBufferNs(v)
	})
}

// UpdateCloseBookingBufferNs sets the "close_booking_buffer_ns" field to the value that was provided on create.
func (u *FlightUpsertBulk) UpdateCloseBookingBufferNs() *FlightUpsertBulk {
	return u.Update(func(s *FlightUpsert) {
		s.UpdateCloseBookingBufferNs()
	})
}

// Exec executes the query.
func (u *FlightUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FlightCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FlightCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FlightUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
