// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flightseat"
)

// FlightSeat is the model entity for the FlightSeat schema.
type FlightSeat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FlightID holds the value of the "flight_id" field.
	FlightID string `json:"flight_id,omitempty"`
	// SeatNumber holds the value of the "seat_number" field.
	SeatNumber string `json:"seat_number,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// PassengerID holds the value of the "passenger_id" field.
	PassengerID string `json:"passenger_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlightSeatQuery when eager-loading is set.
	Edges        FlightSeatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FlightSeatEdges holds the relations/edges for other nodes in the graph.
type FlightSeatEdges struct {
	// Flight holds the value of the flight edge.
	Flight *Flight `json:"flight,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FlightOrErr returns the Flight value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlightSeatEdges) FlightOrErr() (*Flight, error) {
	if e.Flight != nil {
		return e.Flight, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: flight.Label}
	}
	return nil, &NotLoadedError{edge: "flight"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FlightSeat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flightseat.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case flightseat.FieldID:
			values[i] = new(sql.NullInt64)
		case flightseat.FieldFlightID, flightseat.FieldSeatNumber, flightseat.FieldPassengerID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FlightSeat fields.
func (_m *FlightSeat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flightseat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case flightseat.FieldFlightID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flight_id", values[i])
			} else if value.Valid {
				_m.FlightID = value.String
			}
		case flightseat.FieldSeatNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seat_number", values[i])
			} else if value.Valid {
				_m.SeatNumber = value.String
			}
		case flightseat.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case flightseat.FieldPassengerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passenger_id", values[i])
			} else if value.Valid {
				_m.PassengerID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FlightSeat.
// This includes values selected through modifiers, order, etc.
func (_m *FlightSeat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFlight queries the "flight" edge of the FlightSeat entity.
func (_m *FlightSeat) QueryFlight() *FlightQuery {
	return NewFlightSeatClient(_m.config).QueryFlight(_m)
}

// Update returns a builder for updating this FlightSeat.
// Note that you need to call FlightSeat.Unwrap() before calling this method if this FlightSeat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FlightSeat) Update() *FlightSeatUpdateOne {
	return NewFlightSeatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FlightSeat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FlightSeat) Unwrap() *FlightSeat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FlightSeat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FlightSeat) String() string {
	var builder strings.Builder
	builder.WriteString("FlightSeat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("flight_id=")
	builder.WriteString(_m.FlightID)
	builder.WriteString(", ")
	builder.WriteString("seat_number=")
	builder.WriteString(_m.SeatNumber)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("passenger_id=")
	builder.WriteString(_m.PassengerID)
	builder.WriteByte(')')
	return builder.String()
}

// FlightSeats is a parsable slice of FlightSeat.
type FlightSeats []*FlightSeat
