// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/aircraft"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
)

// Flight is the model entity for the Flight schema.
type Flight struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Origin holds the value of the "origin" field.
	Origin string `json:"origin,omitempty"`
	// Destination holds the value of the "destination" field.
	Destination string `json:"destination,omitempty"`
	// ScheduledDeparture holds the value of the "scheduled_departure" field.
	ScheduledDeparture time.Time `json:"scheduled_departure,omitempty"`
	// ScheduledArrival holds the value of the "scheduled_arrival" field.
	ScheduledArrival time.Time `json:"scheduled_arrival,omitempty"`
	// CloseBookingBufferNs holds the value of the "close_booking_buffer_ns" field.
	CloseBookingBufferNs int64 `json:"close_booking_buffer_ns,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlightQuery when eager-loading is set.
	Edges            FlightEdges `json:"edges"`
	aircraft_flights *string
	selectValues     sql.SelectValues
}

// FlightEdges holds the relations/edges for other nodes in the graph.
type FlightEdges struct {
	// Aircraft holds the value of the aircraft edge.
	Aircraft *Aircraft `json:"aircraft,omitempty"`
	// Seats holds the value of the seats edge.
	Seats []*FlightSeat `json:"seats,omitempty"`
	// Tickets holds the value of the tickets edge.
	Tickets []*Ticket `json:"tickets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AircraftOrErr returns the Aircraft value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlightEdges) AircraftOrErr() (*Aircraft, error) {
	if e.Aircraft != nil {
		return e.Aircraft, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aircraft.Label}
	}
	return nil, &NotLoadedError{edge: "aircraft"}
}

// SeatsOrErr returns the Seats value or an error if the edge
// was not loaded in eager-loading.
func (e FlightEdges) SeatsOrErr() ([]*FlightSeat, error) {
	if e.loadedTypes[1] {
		return e.Seats, nil
	}
	return nil, &NotLoadedError{edge: "seats"}
}

// TicketsOrErr returns the Tickets value or an error if the edge
// was not loaded in eager-loading.
func (e FlightEdges) TicketsOrErr() ([]*Ticket, error) {
	if e.loadedTypes[2] {
		return e.Tickets, nil
	}
	return nil, &NotLoadedError{edge: "tickets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Flight) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flight.FieldCloseBookingBufferNs:
			values[i] = new(sql.NullInt64)
		case flight.FieldID, flight.FieldOrigin, flight.FieldDestination:
			values[i] = new(sql.NullString)
		case flight.FieldScheduledDeparture, flight.FieldScheduledArrival:
			values[i] = new(sql.NullTime)
		case flight.ForeignKeys[0]: // aircraft_flights
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Flight fields.
func (_m *Flight) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flight.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case flight.FieldOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin", values[i])
			} else if value.Valid {
				_m.Origin = value.String
			}
		case flight.FieldDestination:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination", values[i])
			} else if value.Valid {
				_m.Destination = value.String
			}
		case flight.FieldScheduledDeparture:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_departure", values[i])
			} else if value.Valid {
				_m.ScheduledDeparture = value.Time
			}
		case flight.FieldScheduledArrival:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_arrival", values[i])
			} else if value.Valid {
				_m.ScheduledArrival = value.Time
			}
		case flight.FieldCloseBookingBufferNs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field close_booking_buffer_ns", values[i])
			} else if value.Valid {
				_m.CloseBookingBufferNs = value.Int64
			}
		case flight.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aircraft_flights", values[i])
			} else if value.Valid {
				_m.aircraft_flights = new(string)
				*_m.aircraft_flights = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Flight.
// This includes values selected through modifiers, order, etc.
func (_m *Flight) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAircraft queries the "aircraft" edge of the Flight entity.
func (_m *Flight) QueryAircraft() *AircraftQuery {
	return NewFlightClient(_m.config).QueryAircraft(_m)
}

// QuerySeats queries the "seats" edge of the Flight entity.
func (_m *Flight) QuerySeats() *FlightSeatQuery {
	return NewFlightClient(_m.config).QuerySeats(_m)
}

// QueryTickets queries the "tickets" edge of the Flight entity.
func (_m *Flight) QueryTickets() *TicketQuery {
	return NewFlightClient(_m.config).QueryTickets(_m)
}

// Update returns a builder for updating this Flight.
// Note that you need to call Flight.Unwrap() before calling this method if this Flight
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Flight) Update() *FlightUpdateOne {
	return NewFlightClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Flight entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Flight) Unwrap() *Flight {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Flight is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Flight) String() string {
	var builder strings.Builder
	builder.WriteString("Flight(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("origin=")
	builder.WriteString(_m.Origin)
	builder.WriteString(", ")
	builder.WriteString("destination=")
	builder.WriteString(_m.Destination)
	builder.WriteString(", ")
	builder.WriteString("scheduled_departure=")
	builder.WriteString(_m.ScheduledDeparture.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scheduled_arrival=")
	builder.WriteString(_m.ScheduledArrival.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("close_booking_buffer_ns=")
	builder.WriteString(fmt.Sprintf("%v", _m.CloseBookingBufferNs))
	builder.WriteByte(')')
	return builder.String()
}

// Flights is a parsable slice of Flight.
type Flights []*Flight
