// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flightseat"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
)

// FlightSeatUpdate is the builder for updating FlightSeat entities.
type FlightSeatUpdate struct {
	config
	hooks    []Hook
	mutation *FlightSeatMutation
}

// Where appends a list predicates to the FlightSeatUpdate builder.
func (_u *FlightSeatUpdate) Where(ps ...predicate.FlightSeat) *FlightSeatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFlightID sets the "flight_id" field.
func (_u *FlightSeatUpdate) SetFlightID(v string) *FlightSeatUpdate {
	_u.mutation.SetFlightID(v)
	return _u
}

// SetNillableFlightID sets the "flight_id" field if the given value is not nil.
func (_u *FlightSeatUpdate) SetNillableFlightID(v *string) *FlightSeatUpdate {
	if v != nil {
		_u.SetFlightID(*v)
	}
	return _u
}

// SetSeatNumber sets the "seat_number" field.
func (_u *FlightSeatUpdate) SetSeatNumber(v string) *FlightSeatUpdate {
	_u.mutation.SetSeatNumber(v)
	return _u
}

// SetNillableSeatNumber sets the "seat_number" field if the given value is not nil.
func (_u *FlightSeatUpdate) SetNillableSeatNumber(v *string) *FlightSeatUpdate {
	if v != nil {
		_u.SetSeatNumber(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *FlightSeatUpdate) SetPrice(v float64) *FlightSeatUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *FlightSeatUpdate) SetNillablePrice(v *float64) *FlightSeatUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *FlightSeatUpdate) AddPrice(v float64) *FlightSeatUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetPassengerID sets the "passenger_id" field.
func (_u *FlightSeatUpdate) SetPassengerID(v string) *FlightSeatUpdate {
	_u.mutation.SetPassengerID(v)
	return _u
}

// SetNillablePassengerID sets the "passenger_id" field if the given value is not nil.
func (_u *FlightSeatUpdate) SetNillablePassengerID(v *string) *FlightSeatUpdate {
	if v != nil {
		_u.SetPassengerID(*v)
	}
	return _u
}

// ClearPassengerID clears the value of the "passenger_id" field.
func (_u *FlightSeatUpdate) ClearPassengerID() *FlightSeatUpdate {
	_u.mutation.ClearPassengerID()
	return _u
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_u *FlightSeatUpdate) SetFlight(v *Flight) *FlightSeatUpdate {
	return _u.SetFlightID(v.ID)
}

// Mutation returns the FlightSeatMutation object of the builder.
func (_u *FlightSeatUpdate) Mutation() *FlightSeatMutation {
	return _u.mutation
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (_u *FlightSeatUpdate) ClearFlight() *FlightSeatUpdate {
	_u.mutation.ClearFlight()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlightSeatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlightSeatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlightSeatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlightSeatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlightSeatUpdate) check() error {
	if v, ok := _u.mutation.SeatNumber(); ok {
		if err := flightseat.SeatNumberValidator(v); err != nil {
			return &ValidationError{Name: "seat_number", err: fmt.Errorf(`ent: validator failed for field "FlightSeat.seat_number": %w`, err)}
		}
	}
	if _u.mutation.FlightCleared() && len(_u.mutation.FlightIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlightSeat.flight"`)
	}
	return nil
}

func (_u *FlightSeatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flightseat.Table, flightseat.Columns, sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SeatNumber(); ok {
		_spec.SetField(flightseat.FieldSeatNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(flightseat.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(flightseat.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PassengerID(); ok {
		_spec.SetField(flightseat.FieldPassengerID, field.TypeString, value)
	}
	if _u.mutation.PassengerIDCleared() {
		_spec.ClearField(flightseat.FieldPassengerID, field.TypeString)
	}
	if _u.mutation.FlightCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flightseat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlightSeatUpdateOne is the builder for updating a single FlightSeat entity.
type FlightSeatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightSeatMutation
}

// SetFlightID sets the "flight_id" field.
func (_u *FlightSeatUpdateOne) SetFlightID(v string) *FlightSeatUpdateOne {
	_u.mutation.SetFlightID(v)
	return _u
}

// SetNillableFlightID sets the "flight_id" field if the given value is not nil.
func (_u *FlightSeatUpdateOne) SetNillableFlightID(v *string) *FlightSeatUpdateOne {
	if v != nil {
		_u.SetFlightID(*v)
	}
	return _u
}

// SetSeatNumber sets the "seat_number" field.
func (_u *FlightSeatUpdateOne) SetSeatNumber(v string) *FlightSeatUpdateOne {
	_u.mutation.SetSeatNumber(v)
	return _u
}

// SetNillableSeatNumber sets the "seat_number" field if the given value is not nil.
func (_u *FlightSeatUpdateOne) SetNillableSeatNumber(v *string) *FlightSeatUpdateOne {
	if v != nil {
		_u.SetSeatNumber(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *FlightSeatUpdateOne) SetPrice(v float64) *FlightSeatUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *FlightSeatUpdateOne) SetNillablePrice(v *float64) *FlightSeatUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *FlightSeatUpdateOne) AddPrice(v float64) *FlightSeatUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetPassengerID sets the "passenger_id" field.
func (_u *FlightSeatUpdateOne) SetPassengerID(v string) *FlightSeatUpdateOne {
	_u.mutation.SetPassengerID(v)
	return _u
}

// SetNillablePassengerID sets the "passenger_id" field if the given value is not nil.
func (_u *FlightSeatUpdateOne) SetNillablePassengerID(v *string) *FlightSeatUpdateOne {
	if v != nil {
		_u.SetPassengerID(*v)
	}
	return _u
}

// ClearPassengerID clears the value of the "passenger_id" field.
func (_u *FlightSeatUpdateOne) ClearPassengerID() *FlightSeatUpdateOne {
	_u.mutation.ClearPassengerID()
	return _u
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_u *FlightSeatUpdateOne) SetFlight(v *Flight) *FlightSeatUpdateOne {
	return _u.SetFlightID(v.ID)
}

// Mutation returns the FlightSeatMutation object of the builder.
func (_u *FlightSeatUpdateOne) Mutation() *FlightSeatMutation {
	return _u.mutation
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (_u *FlightSeatUpdateOne) ClearFlight() *FlightSeatUpdateOne {
	_u.mutation.ClearFlight()
	return _u
}

// Where appends a list predicates to the FlightSeatUpdate builder.
func (_u *FlightSeatUpdateOne) Where(ps ...predicate.FlightSeat) *FlightSeatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlightSeatUpdateOne) Select(field string, fields ...string) *FlightSeatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FlightSeat entity.
func (_u *FlightSeatUpdateOne) Save(ctx context.Context) (*FlightSeat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlightSeatUpdateOne) SaveX(ctx context.Context) *FlightSeat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlightSeatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlightSeatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlightSeatUpdateOne) check() error {
	if v, ok := _u.mutation.SeatNumber(); ok {
		if err := flightseat.SeatNumberValidator(v); err != nil {
			return &ValidationError{Name: "seat_number", err: fmt.Errorf(`ent: validator failed for field "FlightSeat.seat_number": %w`, err)}
		}
	}
	if _u.mutation.FlightCleared() && len(_u.mutation.FlightIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlightSeat.flight"`)
	}
	return nil
}

func (_u *FlightSeatUpdateOne) sqlSave(ctx context.Context) (_node *FlightSeat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flightseat.Table, flightseat.Columns, sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FlightSeat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flightseat.FieldID)
		for _, f := range fields {
			if !flightseat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flightseat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SeatNumber(); ok {
		_spec.SetField(flightseat.FieldSeatNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(flightseat.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(flightseat.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PassengerID(); ok {
		_spec.SetField(flightseat.FieldPassengerID, field.TypeString, value)
	}
	if _u.mutation.PassengerIDCleared() {
		_spec.ClearField(flightseat.FieldPassengerID, field.TypeString)
	}
	if _u.mutation.FlightCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FlightSeat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flightseat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
