// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flightseat"
)

// FlightSeatCreate is the builder for creating a FlightSeat entity.
type FlightSeatCreate struct {
	config
	mutation *FlightSeatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetFlightID sets the "flight_id" field.
func (_c *FlightSeatCreate) SetFlightID(v string) *FlightSeatCreate {
	_c.mutation.SetFlightID(v)
	return _c
}

// SetSeatNumber sets the "seat_number" field.
func (_c *FlightSeatCreate) SetSeatNumber(v string) *FlightSeatCreate {
	_c.mutation.SetSeatNumber(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *FlightSeatCreate) SetPrice(v float64) *FlightSeatCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetPassengerID sets the "passenger_id" field.
func (_c *FlightSeatCreate) SetPassengerID(v string) *FlightSeatCreate {
	_c.mutation.SetPassengerID(v)
	return _c
}

// SetNillablePassengerID sets the "passenger_id" field if the given value is not nil.
func (_c *FlightSeatCreate) SetNillablePassengerID(v *string) *FlightSeatCreate {
	if v != nil {
		_c.SetPassengerID(*v)
	}
	return _c
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_c *FlightSeatCreate) SetFlight(v *Flight) *FlightSeatCreate {
	return _c.SetFlightID(v.ID)
}

// Mutation returns the FlightSeatMutation object of the builder.
func (_c *FlightSeatCreate) Mutation() *FlightSeatMutation {
	return _c.mutation
}

// Save creates the FlightSeat in the database.
func (_c *FlightSeatCreate) Save(ctx context.Context) (*FlightSeat, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FlightSeatCreate) SaveX(ctx context.Context) *FlightSeat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlightSeatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlightSeatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FlightSeatCreate) check() error {
	if _, ok := _c.mutation.FlightID(); !ok {
		return &ValidationError{Name: "flight_id", err: errors.New(`ent: missing required field "FlightSeat.flight_id"`)}
	}
	if _, ok := _c.mutation.SeatNumber(); !ok {
		return &ValidationError{Name: "seat_number", err: errors.New(`ent: missing required field "FlightSeat.seat_number"`)}
	}
	if v, ok := _c.mutation.SeatNumber(); ok {
		if err := flightseat.SeatNumberValidator(v); err != nil {
			return &ValidationError{Name: "seat_number", err: fmt.Errorf(`ent: validator failed for field "FlightSeat.seat_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "FlightSeat.price"`)}
	}
	if len(_c.mutation.FlightIDs()) == 0 {
		return &ValidationError{Name: "flight", err: errors.New(`ent: missing required edge "FlightSeat.flight"`)}
	}
	return nil
}

func (_c *FlightSeatCreate) sqlSave(ctx context.Context) (*FlightSeat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FlightSeatCreate) createSpec() (*FlightSeat, *sqlgraph.CreateSpec) {
	var (
		_node = &FlightSeat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(flightseat.Table, sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SeatNumber(); ok {
		_spec.SetField(flightseat.FieldSeatNumber, field.TypeString, value)
		_node.SeatNumber = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(flightseat.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.PassengerID(); ok {
		_spec.SetField(flightseat.FieldPassengerID, field.TypeString, value)
		_node.PassengerID = value
	}
	if nodes := _c.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FlightID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FlightSeat.Create().
//		SetFlightID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FlightSeatUpsert) {
//			SetFlightID(v+v).
//		}).
//		Exec(ctx)
func (_c *FlightSeatCreate) OnConflict(opts ...sql.ConflictOption) *FlightSeatUpsertOne {
	_c.conflict = opts
	return &FlightSeatUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FlightSeat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FlightSeatCreate) OnConflictColumns(columns ...string) *FlightSeatUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FlightSeatUpsertOne{
		create: _c,
	}
}

type (
	// FlightSeatUpsertOne is the builder for "upsert"-ing
	//  one FlightSeat node.
	FlightSeatUpsertOne struct {
		create *FlightSeatCreate
	}

	// FlightSeatUpsert is the "OnConflict" setter.
	FlightSeatUpsert struct {
		*sql.UpdateSet
	}
)

// SetFlightID sets the "flight_id" field.
func (u *FlightSeatUpsert) SetFlightID(v string) *FlightSeatUpsert {
	u.Set(flightseat.FieldFlightID, v)
	return u
}

// UpdateFlightID sets the "flight_id" field to the value that was provided on create.
func (u *FlightSeatUpsert) UpdateFlightID() *FlightSeatUpsert {
	u.SetExcluded(flightseat.FieldFlightID)
	return u
}

// SetSeatNumber sets the "seat_number" field.
func (u *FlightSeatUpsert) SetSeatNumber(v string) *FlightSeatUpsert {
	u.Set(flightseat.FieldSeatNumber, v)
	return u
}

// UpdateSeatNumber sets the "seat_number" field to the value that was provided on create.
func (u *FlightSeatUpsert) UpdateSeatNumber() *FlightSeatUpsert {
	u.SetExcluded(flightseat.FieldSeatNumber)
	return u
}

// SetPrice sets the "price" field.
func (u *FlightSeatUpsert) SetPrice(v float64) *FlightSeatUpsert {
	u.Set(flightseat.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *FlightSeatUpsert) UpdatePrice() *FlightSeatUpsert {
	u.SetExcluded(flightseat.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *FlightSeatUpsert) AddPrice(v float64) *FlightSeatUpsert {
	u.Add(flightseat.FieldPrice, v)
	return u
}

// SetPassengerID sets the "passenger_id" field.
func (u *FlightSeatUpsert) SetPassengerID(v string) *FlightSeatUpsert {
	u.Set(flightseat.FieldPassengerID, v)
	return u
}

// UpdatePassengerID sets the "passenger_id" field to the value that was provided on create.
func (u *FlightSeatUpsert) UpdatePassengerID() *FlightSeatUpsert {
	u.SetExcluded(flightseat.FieldPassengerID)
	return u
}

// ClearPassengerID clears the value of the "passenger_id" field.
func (u *FlightSeatUpsert) ClearPassengerID() *FlightSeatUpsert {
	u.SetNull(flightseat.FieldPassengerID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FlightSeat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FlightSeatUpsertOne) UpdateNewValues() *FlightSeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FlightSeat.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FlightSeatUpsertOne) Ignore() *FlightSeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FlightSeatUpsertOne) DoNothing() *FlightSeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FlightSeatCreate.OnConflict
// documentation for more info.
func (u *FlightSeatUpsertOne) Update(set func(*FlightSeatUpsert)) *FlightSeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FlightSeatUpsert{UpdateSet: update})
	}))
	return u
}

// SetFlightID sets the "flight_id" field.
func (u *FlightSeatUpsertOne) SetFlightID(v string) *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.SetFlightID(v)
	})
}

// UpdateFlightID sets the "flight_id" field to the value that was provided on create.
func (u *FlightSeatUpsertOne) UpdateFlightID() *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.UpdateFlightID()
	})
}

// SetSeatNumber sets the "seat_number" field.
func (u *FlightSeatUpsertOne) SetSeatNumber(v string) *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.SetSeatNumber(v)
	})
}

// UpdateSeatNumber sets the "seat_number" field to the value that was provided on create.
func (u *FlightSeatUpsertOne) UpdateSeatNumber() *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.UpdateSeatNumber()
	})
}

// SetPrice sets the "price" field.
func (u *FlightSeatUpsertOne) SetPrice(v float64) *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *FlightSeatUpsertOne) AddPrice(v float64) *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *FlightSeatUpsertOne) UpdatePrice() *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.UpdatePrice()
	})
}

// SetPassengerID sets the "passenger_id" field.
func (u *FlightSeatUpsertOne) SetPassengerID(v string) *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.SetPassengerID(v)
	})
}

// UpdatePassengerID sets the "passenger_id" field to the value that was provided on create.
func (u *FlightSeatUpsertOne) UpdatePassengerID() *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.UpdatePassengerID()
	})
}

// ClearPassengerID clears the value of the "passenger_id" field.
func (u *FlightSeatUpsertOne) ClearPassengerID() *FlightSeatUpsertOne {
	return u.Update(func(s *FlightSeatUpsert) {
		s.ClearPassengerID()
	})
}

// Exec executes the query.
func (u *FlightSeatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FlightSeatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FlightSeatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FlightSeatUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FlightSeatUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FlightSeatCreateBulk is the builder for creating many FlightSeat entities in bulk.
type FlightSeatCreateBulk struct {
	config
	err      error
	builders []*FlightSeatCreate
	conflict []sql.ConflictOption
}

// Save creates the FlightSeat entities in the database.
func (_c *FlightSeatCreateBulk) Save(ctx context.Context) ([]*FlightSeat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FlightSeat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlightSeatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FlightSeatCreateBulk) SaveX(ctx context.Context) []*FlightSeat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlightSeatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlightSeatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FlightSeat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FlightSeatUpsert) {
//			SetFlightID(v+v).
//		}).
//		Exec(ctx)
func (_c *FlightSeatCreateBulk) OnConflict(opts ...sql.ConflictOption) *FlightSeatUpsertBulk {
	_c.conflict = opts
	return &FlightSeatUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FlightSeat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FlightSeatCreateBulk) OnConflictColumns(columns ...string) *FlightSeatUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FlightSeatUpsertBulk{
		create: _c,
	}
}

// FlightSeatUpsertBulk is the builder for "upsert"-ing
// a bulk of FlightSeat nodes.
type FlightSeatUpsertBulk struct {
	create *FlightSeatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FlightSeat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FlightSeatUpsertBulk) UpdateNewValues() *FlightSeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FlightSeat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FlightSeatUpsertBulk) Ignore() *FlightSeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FlightSeatUpsertBulk) DoNothing() *FlightSeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FlightSeatCreateBulk.OnConflict
// documentation for more info.
func (u *FlightSeatUpsertBulk) Update(set func(*FlightSeatUpsert)) *FlightSeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FlightSeatUpsert{UpdateSet: update})
	}))
	return u
}

// SetFlightID sets the "flight_id" field.
func (u *FlightSeatUpsertBulk) SetFlightID(v string) *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.SetFlightID(v)
	})
}

// UpdateFlightID sets the "flight_id" field to the value that was provided on create.
func (u *FlightSeatUpsertBulk) UpdateFlightID() *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.UpdateFlightID()
	})
}

// SetSeatNumber sets the "seat_number" field.
func (u *FlightSeatUpsertBulk) SetSeatNumber(v string) *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.SetSeatNumber(v)
	})
}

// UpdateSeatNumber sets the "seat_number" field to the value that was provided on create.
func (u *FlightSeatUpsertBulk) UpdateSeatNumber() *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.UpdateSeatNumber()
	})
}

// SetPrice sets the "price" field.
func (u *FlightSeatUpsertBulk) SetPrice(v float64) *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *FlightSeatUpsertBulk) AddPrice(v float64) *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *FlightSeatUpsertBulk) UpdatePrice() *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.UpdatePrice()
	})
}

// SetPassengerID sets the "passenger_id" field.
func (u *FlightSeatUpsertBulk) SetPassengerID(v string) *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.SetPassengerID(v)
	})
}

// UpdatePassengerID sets the "passenger_id" field to the value that was provided on create.
func (u *FlightSeatUpsertBulk) UpdatePassengerID() *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.UpdatePassengerID()
	})
}

// ClearPassengerID clears the value of the "passenger_id" field.
func (u *FlightSeatUpsertBulk) ClearPassengerID() *FlightSeatUpsertBulk {
	return u.Update(func(s *FlightSeatUpsert) {
		s.ClearPassengerID()
	})
}

// Exec executes the query.
func (u *FlightSeatUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FlightSeatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FlightSeatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FlightSeatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
