// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/aircraft"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flightseat"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/ticket"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAircraft   = "Aircraft"
	TypeFlight     = "Flight"
	TypeFlightSeat = "FlightSeat"
	TypeTicket     = "Ticket"
)

// AircraftMutation represents an operation that mutates the Aircraft nodes in the graph.
type AircraftMutation struct {
	config
	op             Op
	typ            string
	id             *string
	seats          *[]string
	appendseats    []string
	clearedFields  map[string]struct{}
	flights        map[string]struct{}
	removedflights map[string]struct{}
	clearedflights bool
	done           bool
	oldValue       func(context.Context) (*Aircraft, error)
	predicates     []predicate.Aircraft
}

var _ ent.Mutation = (*AircraftMutation)(nil)

// aircraftOption allows management of the mutation configuration using functional options.
type aircraftOption func(*AircraftMutation)

// newAircraftMutation creates new mutation for the Aircraft entity.
func newAircraftMutation(c config, op Op, opts ...aircraftOption) *AircraftMutation {
	m := &AircraftMutation{
		config:        c,
		op:            op,
		typ:           TypeAircraft,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAircraftID sets the ID field of the mutation.
func withAircraftID(id string) aircraftOption {
	return func(m *AircraftMutation) {
		var (
			err   error
			once  sync.Once
			value *Aircraft
		)
		m.oldValue = func(ctx context.Context) (*Aircraft, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Aircraft.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAircraft sets the old Aircraft of the mutation.
func withAircraft(node *Aircraft) aircraftOption {
	return func(m *AircraftMutation) {
		m.oldValue = func(context.Context) (*Aircraft, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AircraftMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AircraftMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Aircraft entities.
func (m *AircraftMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AircraftMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AircraftMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Aircraft.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSeats sets the "seats" field.
func (m *AircraftMutation) SetSeats(s []string) {
	m.seats = &s
	m.appendseats = nil
}

// Seats returns the value of the "seats" field in the mutation.
func (m *AircraftMutation) Seats() (r []string, exists bool) {
	v := m.seats
	if v == nil {
		return
	}
	return *v, true
}

// OldSeats returns the old "seats" field's value of the Aircraft entity.
// If the Aircraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AircraftMutation) OldSeats(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeats is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeats requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeats: %w", err)
	}
	return oldValue.Seats, nil
}

// AppendSeats adds s to the "seats" field.
func (m *AircraftMutation) AppendSeats(s []string) {
	m.appendseats = append(m.appendseats, s...)
}

// AppendedSeats returns the list of values that were appended to the "seats" field in this mutation.
func (m *AircraftMutation) AppendedSeats() ([]string, bool) {
	if len(m.appendseats) == 0 {
		return nil, false
	}
	return m.appendseats, true
}

// ResetSeats resets all changes to the "seats" field.
func (m *AircraftMutation) ResetSeats() {
	m.seats = nil
	m.appendseats = nil
}

// AddFlightIDs adds the "flights" edge to the Flight entity by ids.
func (m *AircraftMutation) AddFlightIDs(ids ...string) {
	if m.flights == nil {
		m.flights = make(map[string]struct{})
	}
	for i := range ids {
		m.flights[ids[i]] = struct{}{}
	}
}

// ClearFlights clears the "flights" edge to the Flight entity.
func (m *AircraftMutation) ClearFlights() {
	m.clearedflights = true
}

// FlightsCleared reports if the "flights" edge to the Flight entity was cleared.
func (m *AircraftMutation) FlightsCleared() bool {
	return m.clearedflights
}

// RemoveFlightIDs removes the "flights" edge to the Flight entity by IDs.
func (m *AircraftMutation) RemoveFlightIDs(ids ...string) {
	if m.removedflights == nil {
		m.removedflights = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.flights, ids[i])
		m.removedflights[ids[i]] = struct{}{}
	}
}

// RemovedFlights returns the removed IDs of the "flights" edge to the Flight entity.
func (m *AircraftMutation) RemovedFlightsIDs() (ids []string) {
	for id := range m.removedflights {
		ids = append(ids, id)
	}
	return
}

// FlightsIDs returns the "flights" edge IDs in the mutation.
func (m *AircraftMutation) FlightsIDs() (ids []string) {
	for id := range m.flights {
		ids = append(ids, id)
	}
	return
}

// ResetFlights resets all changes to the "flights" edge.
func (m *AircraftMutation) ResetFlights() {
	m.flights = nil
	m.clearedflights = false
	m.removedflights = nil
}

// Where appends a list predicates to the AircraftMutation builder.
func (m *AircraftMutation) Where(ps ...predicate.Aircraft) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AircraftMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AircraftMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Aircraft, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AircraftMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AircraftMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Aircraft).
func (m *AircraftMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AircraftMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.seats != nil {
		fields = append(fields, aircraft.FieldSeats)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AircraftMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case aircraft.FieldSeats:
		return m.Seats()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AircraftMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case aircraft.FieldSeats:
		return m.OldSeats(ctx)
	}
	return nil, fmt.Errorf("unknown Aircraft field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AircraftMutation) SetField(name string, value ent.Value) error {
	switch name {
	case aircraft.FieldSeats:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeats(v)
		return nil
	}
	return fmt.Errorf("unknown Aircraft field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AircraftMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AircraftMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AircraftMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Aircraft numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AircraftMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AircraftMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AircraftMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Aircraft nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AircraftMutation) ResetField(name string) error {
	switch name {
	case aircraft.FieldSeats:
		m.ResetSeats()
		return nil
	}
	return fmt.Errorf("unknown Aircraft field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AircraftMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.flights != nil {
		edges = append(edges, aircraft.EdgeFlights)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AircraftMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case aircraft.EdgeFlights:
		ids := make([]ent.Value, 0, len(m.flights))
		for id := range m.flights {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AircraftMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedflights != nil {
		edges = append(edges, aircraft.EdgeFlights)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AircraftMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case aircraft.EdgeFlights:
		ids := make([]ent.Value, 0, len(m.removedflights))
		for id := range m.removedflights {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AircraftMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedflights {
		edges = append(edges, aircraft.EdgeFlights)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AircraftMutation) EdgeCleared(name string) bool {
	switch name {
	case aircraft.EdgeFlights:
		return m.clearedflights
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AircraftMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Aircraft unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AircraftMutation) ResetEdge(name string) error {
	switch name {
	case aircraft.EdgeFlights:
		m.ResetFlights()
		return nil
	}
	return fmt.Errorf("unknown Aircraft edge %s", name)
}

// FlightMutation represents an operation that mutates the Flight nodes in the graph.
type FlightMutation struct {
	config
	op                         Op
	typ                        string
	id                         *string
	origin                     *string
	destination                *string
	scheduled_departure        *time.Time
	scheduled_arrival          *time.Time
	close_booking_buffer_ns    *int64
	addclose_booking_buffer_ns *int64
	clearedFields              map[string]struct{}
	aircraft                   *string
	clearedaircraft            bool
	seats                      map[int]struct{}
	removedseats               map[int]struct{}
	clearedseats               bool
	tickets                    map[string]struct{}
	removedtickets             map[string]struct{}
	clearedtickets             bool
	done                       bool
	oldValue                   func(context.Context) (*Flight, error)
	predicates                 []predicate.Flight
}

var _ ent.Mutation = (*FlightMutation)(nil)

// flightOption allows management of the mutation configuration using functional options.
type flightOption func(*FlightMutation)

// newFlightMutation creates new mutation for the Flight entity.
func newFlightMutation(c config, op Op, opts ...flightOption) *FlightMutation {
	m := &FlightMutation{
		config:        c,
		op:            op,
		typ:           TypeFlight,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFlightID sets the ID field of the mutation.
func withFlightID(id string) flightOption {
	return func(m *FlightMutation) {
		var (
			err   error
			once  sync.Once
			value *Flight
		)
		m.oldValue = func(ctx context.Context) (*Flight, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Flight.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFlight sets the old Flight of the mutation.
func withFlight(node *Flight) flightOption {
	return func(m *FlightMutation) {
		m.oldValue = func(context.Context) (*Flight, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FlightMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FlightMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Flight entities.
func (m *FlightMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FlightMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FlightMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Flight.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetOrigin sets the "origin" field.
func (m *FlightMutation) SetOrigin(s string) {
	m.origin = &s
}

// Origin returns the value of the "origin" field in the mutation.
func (m *FlightMutation) Origin() (r string, exists bool) {
	v := m.origin
	if v == nil {
		return
	}
	return *v, true
}

// OldOrigin returns the old "origin" field's value of the Flight entity.
// If the Flight object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightMutation) OldOrigin(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrigin is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrigin requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrigin: %w", err)
	}
	return oldValue.Origin, nil
}

// ResetOrigin resets all changes to the "origin" field.
func (m *FlightMutation) ResetOrigin() {
	m.origin = nil
}

// SetDestination sets the "destination" field.
func (m *FlightMutation) SetDestination(s string) {
	m.destination = &s
}

// Destination returns the value of the "destination" field in the mutation.
func (m *FlightMutation) Destination() (r string, exists bool) {
	v := m.destination
	if v == nil {
		return
	}
	return *v, true
}

// OldDestination returns the old "destination" field's value of the Flight entity.
// If the Flight object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightMutation) OldDestination(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDestination is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDestination requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDestination: %w", err)
	}
	return oldValue.Destination, nil
}

// ResetDestination resets all changes to the "destination" field.
func (m *FlightMutation) ResetDestination() {
	m.destination = nil
}

// SetScheduledDeparture sets the "scheduled_departure" field.
func (m *FlightMutation) SetScheduledDeparture(t time.Time) {
	m.scheduled_departure = &t
}

// ScheduledDeparture returns the value of the "scheduled_departure" field in the mutation.
func (m *FlightMutation) ScheduledDeparture() (r time.Time, exists bool) {
	v := m.scheduled_departure
	if v == nil {
		return
	}
	return *v, true
}

// OldScheduledDeparture returns the old "scheduled_departure" field's value of the Flight entity.
// If the Flight object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightMutation) OldScheduledDeparture(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScheduledDeparture is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScheduledDeparture requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScheduledDeparture: %w", err)
	}
	return oldValue.ScheduledDeparture, nil
}

// ResetScheduledDeparture resets all changes to the "scheduled_departure" field.
func (m *FlightMutation) ResetScheduledDeparture() {
	m.scheduled_departure = nil
}

// SetScheduledArrival sets the "scheduled_arrival" field.
func (m *FlightMutation) SetScheduledArrival(t time.Time) {
	m.scheduled_arrival = &t
}

// ScheduledArrival returns the value of the "scheduled_arrival" field in the mutation.
func (m *FlightMutation) ScheduledArrival() (r time.Time, exists bool) {
	v := m.scheduled_arrival
	if v == nil {
		return
	}
	return *v, true
}

// OldScheduledArrival returns the old "scheduled_arrival" field's value of the Flight entity.
// If the Flight object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightMutation) OldScheduledArrival(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScheduledArrival is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScheduledArrival requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScheduledArrival: %w", err)
	}
	return oldValue.ScheduledArrival, nil
}

// ResetScheduledArrival resets all changes to the "scheduled_arrival" field.
func (m *FlightMutation) ResetScheduledArrival() {
	m.scheduled_arrival = nil
}

// SetCloseBookingBufferNs sets the "close_booking_buffer_ns" field.
func (m *FlightMutation) SetCloseBookingBufferNs(i int64) {
	m.close_booking_buffer_ns = &i
	m.addclose_booking_buffer_ns = nil
}

// CloseBookingBufferNs returns the value of the "close_booking_buffer_ns" field in the mutation.
func (m *FlightMutation) CloseBookingBufferNs() (r int64, exists bool) {
	v := m.close_booking_buffer_ns
	if v == nil {
		return
	}
	return *v, true
}

// OldCloseBookingBufferNs returns the old "close_booking_buffer_ns" field's value of the Flight entity.
// If the Flight object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightMutation) OldCloseBookingBufferNs(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCloseBookingBufferNs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCloseBookingBufferNs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCloseBookingBufferNs: %w", err)
	}
	return oldValue.CloseBookingBufferNs, nil
}

// AddCloseBookingBufferNs adds i to the "close_booking_buffer_ns" field.
func (m *FlightMutation) AddCloseBookingBufferNs(i int64) {
	if m.addclose_booking_buffer_ns != nil {
		*m.addclose_booking_buffer_ns += i
	} else {
		m.addclose_booking_buffer_ns = &i
	}
}

// AddedCloseBookingBufferNs returns the value that was added to the "close_booking_buffer_ns" field in this mutation.
func (m *FlightMutation) AddedCloseBookingBufferNs() (r int64, exists bool) {
	v := m.addclose_booking_buffer_ns
	if v == nil {
		return
	}
	return *v, true
}

// ResetCloseBookingBufferNs resets all changes to the "close_booking_buffer_ns" field.
func (m *FlightMutation) ResetCloseBookingBufferNs() {
	m.close_booking_buffer_ns = nil
	m.addclose_booking_buffer_ns = nil
}

// SetAircraftID sets the "aircraft" edge to the Aircraft entity by id.
func (m *FlightMutation) SetAircraftID(id string) {
	m.aircraft = &id
}

// ClearAircraft clears the "aircraft" edge to the Aircraft entity.
func (m *FlightMutation) ClearAircraft() {
	m.clearedaircraft = true
}

// AircraftCleared reports if the "aircraft" edge to the Aircraft entity was cleared.
func (m *FlightMutation) AircraftCleared() bool {
	return m.clearedaircraft
}

// AircraftID returns the "aircraft" edge ID in the mutation.
func (m *FlightMutation) AircraftID() (id string, exists bool) {
	if m.aircraft != nil {
		return *m.aircraft, true
	}
	return
}

// AircraftIDs returns the "aircraft" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AircraftID instead. It exists only for internal usage by the builders.
func (m *FlightMutation) AircraftIDs() (ids []string) {
	if id := m.aircraft; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAircraft resets all changes to the "aircraft" edge.
func (m *FlightMutation) ResetAircraft() {
	m.aircraft = nil
	m.clearedaircraft = false
}

// AddSeatIDs adds the "seats" edge to the FlightSeat entity by ids.
func (m *FlightMutation) AddSeatIDs(ids ...int) {
	if m.seats == nil {
		m.seats = make(map[int]struct{})
	}
	for i := range ids {
		m.seats[ids[i]] = struct{}{}
	}
}

// ClearSeats clears the "seats" edge to the FlightSeat entity.
func (m *FlightMutation) ClearSeats() {
	m.clearedseats = true
}

// SeatsCleared reports if the "seats" edge to the FlightSeat entity was cleared.
func (m *FlightMutation) SeatsCleared() bool {
	return m.clearedseats
}

// RemoveSeatIDs removes the "seats" edge to the FlightSeat entity by IDs.
func (m *FlightMutation) RemoveSeatIDs(ids ...int) {
	if m.removedseats == nil {
		m.removedseats = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.seats, ids[i])
		m.removedseats[ids[i]] = struct{}{}
	}
}

// RemovedSeats returns the removed IDs of the "seats" edge to the FlightSeat entity.
func (m *FlightMutation) RemovedSeatsIDs() (ids []int) {
	for id := range m.removedseats {
		ids = append(ids, id)
	}
	return
}

// SeatsIDs returns the "seats" edge IDs in the mutation.
func (m *FlightMutation) SeatsIDs() (ids []int) {
	for id := range m.seats {
		ids = append(ids, id)
	}
	return
}

// ResetSeats resets all changes to the "seats" edge.
func (m *FlightMutation) ResetSeats() {
	m.seats = nil
	m.clearedseats = false
	m.removedseats = nil
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by ids.
func (m *FlightMutation) AddTicketIDs(ids ...string) {
	if m.tickets == nil {
		m.tickets = make(map[string]struct{})
	}
	for i := range ids {
		m.tickets[ids[i]] = struct{}{}
	}
}

// ClearTickets clears the "tickets" edge to the Ticket entity.
func (m *FlightMutation) ClearTickets() {
	m.clearedtickets = true
}

// TicketsCleared reports if the "tickets" edge to the Ticket entity was cleared.
func (m *FlightMutation) TicketsCleared() bool {
	return m.clearedtickets
}

// RemoveTicketIDs removes the "tickets" edge to the Ticket entity by IDs.
func (m *FlightMutation) RemoveTicketIDs(ids ...string) {
	if m.removedtickets == nil {
		m.removedtickets = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.tickets, ids[i])
		m.removedtickets[ids[i]] = struct{}{}
	}
}

// RemovedTickets returns the removed IDs of the "tickets" edge to the Ticket entity.
func (m *FlightMutation) RemovedTicketsIDs() (ids []string) {
	for id := range m.removedtickets {
		ids = append(ids, id)
	}
	return
}

// TicketsIDs returns the "tickets" edge IDs in the mutation.
func (m *FlightMutation) TicketsIDs() (ids []string) {
	for id := range m.tickets {
		ids = append(ids, id)
	}
	return
}

// ResetTickets resets all changes to the "tickets" edge.
func (m *FlightMutation) ResetTickets() {
	m.tickets = nil
	m.clearedtickets = false
	m.removedtickets = nil
}

// Where appends a list predicates to the FlightMutation builder.
func (m *FlightMutation) Where(ps ...predicate.Flight) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FlightMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FlightMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Flight, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FlightMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FlightMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Flight).
func (m *FlightMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FlightMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.origin != nil {
		fields = append(fields, flight.FieldOrigin)
	}
	if m.destination != nil {
		fields = append(fields, flight.FieldDestination)
	}
	if m.scheduled_departure != nil {
		fields = append(fields, flight.FieldScheduledDeparture)
	}
	if m.scheduled_arrival != nil {
		fields = append(fields, flight.FieldScheduledArrival)
	}
	if m.close_booking_buffer_ns != nil {
		fields = append(fields, flight.FieldCloseBookingBufferNs)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FlightMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case flight.FieldOrigin:
		return m.Origin()
	case flight.FieldDestination:
		return m.Destination()
	case flight.FieldScheduledDeparture:
		return m.ScheduledDeparture()
	case flight.FieldScheduledArrival:
		return m.ScheduledArrival()
	case flight.FieldCloseBookingBufferNs:
		return m.CloseBookingBufferNs()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FlightMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case flight.FieldOrigin:
		return m.OldOrigin(ctx)
	case flight.FieldDestination:
		return m.OldDestination(ctx)
	case flight.FieldScheduledDeparture:
		return m.OldScheduledDeparture(ctx)
	case flight.FieldScheduledArrival:
		return m.OldScheduledArrival(ctx)
	case flight.FieldCloseBookingBufferNs:
		return m.OldCloseBookingBufferNs(ctx)
	}
	return nil, fmt.Errorf("unknown Flight field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlightMutation) SetField(name string, value ent.Value) error {
	switch name {
	case flight.FieldOrigin:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrigin(v)
		return nil
	case flight.FieldDestination:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDestination(v)
		return nil
	case flight.FieldScheduledDeparture:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScheduledDeparture(v)
		return nil
	case flight.FieldScheduledArrival:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScheduledArrival(v)
		return nil
	case flight.FieldCloseBookingBufferNs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCloseBookingBufferNs(v)
		return nil
	}
	return fmt.Errorf("unknown Flight field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FlightMutation) AddedFields() []string {
	var fields []string
	if m.addclose_booking_buffer_ns != nil {
		fields = append(fields, flight.FieldCloseBookingBufferNs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FlightMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case flight.FieldCloseBookingBufferNs:
		return m.AddedCloseBookingBufferNs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlightMutation) AddField(name string, value ent.Value) error {
	switch name {
	case flight.FieldCloseBookingBufferNs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCloseBookingBufferNs(v)
		return nil
	}
	return fmt.Errorf("unknown Flight numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FlightMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FlightMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FlightMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Flight nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FlightMutation) ResetField(name string) error {
	switch name {
	case flight.FieldOrigin:
		m.ResetOrigin()
		return nil
	case flight.FieldDestination:
		m.ResetDestination()
		return nil
	case flight.FieldScheduledDeparture:
		m.ResetScheduledDeparture()
		return nil
	case flight.FieldScheduledArrival:
		m.ResetScheduledArrival()
		return nil
	case flight.FieldCloseBookingBufferNs:
		m.ResetCloseBookingBufferNs()
		return nil
	}
	return fmt.Errorf("unknown Flight field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FlightMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.aircraft != nil {
		edges = append(edges, flight.EdgeAircraft)
	}
	if m.seats != nil {
		edges = append(edges, flight.EdgeSeats)
	}
	if m.tickets != nil {
		edges = append(edges, flight.EdgeTickets)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FlightMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case flight.EdgeAircraft:
		if id := m.aircraft; id != nil {
			return []ent.Value{*id}
		}
	case flight.EdgeSeats:
		ids := make([]ent.Value, 0, len(m.seats))
		for id := range m.seats {
			ids = append(ids, id)
		}
		return ids
	case flight.EdgeTickets:
		ids := make([]ent.Value, 0, len(m.tickets))
		for id := range m.tickets {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FlightMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedseats != nil {
		edges = append(edges, flight.EdgeSeats)
	}
	if m.removedtickets != nil {
		edges = append(edges, flight.EdgeTickets)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FlightMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case flight.EdgeSeats:
		ids := make([]ent.Value, 0, len(m.removedseats))
		for id := range m.removedseats {
			ids = append(ids, id)
		}
		return ids
	case flight.EdgeTickets:
		ids := make([]ent.Value, 0, len(m.removedtickets))
		for id := range m.removedtickets {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FlightMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedaircraft {
		edges = append(edges, flight.EdgeAircraft)
	}
	if m.clearedseats {
		edges = append(edges, flight.EdgeSeats)
	}
	if m.clearedtickets {
		edges = append(edges, flight.EdgeTickets)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FlightMutation) EdgeCleared(name string) bool {
	switch name {
	case flight.EdgeAircraft:
		return m.clearedaircraft
	case flight.EdgeSeats:
		return m.clearedseats
	case flight.EdgeTickets:
		return m.clearedtickets
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FlightMutation) ClearEdge(name string) error {
	switch name {
	case flight.EdgeAircraft:
		m.ClearAircraft()
		return nil
	}
	return fmt.Errorf("unknown Flight unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FlightMutation) ResetEdge(name string) error {
	switch name {
	case flight.EdgeAircraft:
		m.ResetAircraft()
		return nil
	case flight.EdgeSeats:
		m.ResetSeats()
		return nil
	case flight.EdgeTickets:
		m.ResetTickets()
		return nil
	}
	return fmt.Errorf("unknown Flight edge %s", name)
}

// FlightSeatMutation represents an operation that mutates the FlightSeat nodes in the graph.
type FlightSeatMutation struct {
	config
	op            Op
	typ           string
	id            *int
	seat_number   *string
	price         *float64
	addprice      *float64
	passenger_id  *string
	clearedFields map[string]struct{}
	flight        *string
	clearedflight bool
	done          bool
	oldValue      func(context.Context) (*FlightSeat, error)
	predicates    []predicate.FlightSeat
}

var _ ent.Mutation = (*FlightSeatMutation)(nil)

// flightseatOption allows management of the mutation configuration using functional options.
type flightseatOption func(*FlightSeatMutation)

// newFlightSeatMutation creates new mutation for the FlightSeat entity.
func newFlightSeatMutation(c config, op Op, opts ...flightseatOption) *FlightSeatMutation {
	m := &FlightSeatMutation{
		config:        c,
		op:            op,
		typ:           TypeFlightSeat,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFlightSeatID sets the ID field of the mutation.
func withFlightSeatID(id int) flightseatOption {
	return func(m *FlightSeatMutation) {
		var (
			err   error
			once  sync.Once
			value *FlightSeat
		)
		m.oldValue = func(ctx context.Context) (*FlightSeat, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().FlightSeat.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFlightSeat sets the old FlightSeat of the mutation.
func withFlightSeat(node *FlightSeat) flightseatOption {
	return func(m *FlightSeatMutation) {
		m.oldValue = func(context.Context) (*FlightSeat, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FlightSeatMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FlightSeatMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FlightSeatMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FlightSeatMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().FlightSeat.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetFlightID sets the "flight_id" field.
func (m *FlightSeatMutation) SetFlightID(s string) {
	m.flight = &s
}

// FlightID returns the value of the "flight_id" field in the mutation.
func (m *FlightSeatMutation) FlightID() (r string, exists bool) {
	v := m.flight
	if v == nil {
		return
	}
	return *v, true
}

// OldFlightID returns the old "flight_id" field's value of the FlightSeat entity.
// If the FlightSeat object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightSeatMutation) OldFlightID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFlightID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFlightID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFlightID: %w", err)
	}
	return oldValue.FlightID, nil
}

// ResetFlightID resets all changes to the "flight_id" field.
func (m *FlightSeatMutation) ResetFlightID() {
	m.flight = nil
}

// SetSeatNumber sets the "seat_number" field.
func (m *FlightSeatMutation) SetSeatNumber(s string) {
	m.seat_number = &s
}

// SeatNumber returns the value of the "seat_number" field in the mutation.
func (m *FlightSeatMutation) SeatNumber() (r string, exists bool) {
	v := m.seat_number
	if v == nil {
		return
	}
	return *v, true
}

// OldSeatNumber returns the old "seat_number" field's value of the FlightSeat entity.
// If the FlightSeat object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightSeatMutation) OldSeatNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeatNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeatNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeatNumber: %w", err)
	}
	return oldValue.SeatNumber, nil
}

// ResetSeatNumber resets all changes to the "seat_number" field.
func (m *FlightSeatMutation) ResetSeatNumber() {
	m.seat_number = nil
}

// SetPrice sets the "price" field.
func (m *FlightSeatMutation) SetPrice(f float64) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *FlightSeatMutation) Price() (r float64, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the FlightSeat entity.
// If the FlightSeat object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightSeatMutation) OldPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *FlightSeatMutation) AddPrice(f float64) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *FlightSeatMutation) AddedPrice() (r float64, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *FlightSeatMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// SetPassengerID sets the "passenger_id" field.
func (m *FlightSeatMutation) SetPassengerID(s string) {
	m.passenger_id = &s
}

// PassengerID returns the value of the "passenger_id" field in the mutation.
func (m *FlightSeatMutation) PassengerID() (r string, exists bool) {
	v := m.passenger_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPassengerID returns the old "passenger_id" field's value of the FlightSeat entity.
// If the FlightSeat object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlightSeatMutation) OldPassengerID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassengerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassengerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassengerID: %w", err)
	}
	return oldValue.PassengerID, nil
}

// ClearPassengerID clears the value of the "passenger_id" field.
func (m *FlightSeatMutation) ClearPassengerID() {
	m.passenger_id = nil
	m.clearedFields[flightseat.FieldPassengerID] = struct{}{}
}

// PassengerIDCleared returns if the "passenger_id" field was cleared in this mutation.
func (m *FlightSeatMutation) PassengerIDCleared() bool {
	_, ok := m.clearedFields[flightseat.FieldPassengerID]
	return ok
}

// ResetPassengerID resets all changes to the "passenger_id" field.
func (m *FlightSeatMutation) ResetPassengerID() {
	m.passenger_id = nil
	delete(m.clearedFields, flightseat.FieldPassengerID)
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (m *FlightSeatMutation) ClearFlight() {
	m.clearedflight = true
	m.clearedFields[flightseat.FieldFlightID] = struct{}{}
}

// FlightCleared reports if the "flight" edge to the Flight entity was cleared.
func (m *FlightSeatMutation) FlightCleared() bool {
	return m.clearedflight
}

// FlightIDs returns the "flight" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// FlightID instead. It exists only for internal usage by the builders.
func (m *FlightSeatMutation) FlightIDs() (ids []string) {
	if id := m.flight; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetFlight resets all changes to the "flight" edge.
func (m *FlightSeatMutation) ResetFlight() {
	m.flight = nil
	m.clearedflight = false
}

// Where appends a list predicates to the FlightSeatMutation builder.
func (m *FlightSeatMutation) Where(ps ...predicate.FlightSeat) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FlightSeatMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FlightSeatMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.FlightSeat, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FlightSeatMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FlightSeatMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (FlightSeat).
func (m *FlightSeatMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FlightSeatMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.flight != nil {
		fields = append(fields, flightseat.FieldFlightID)
	}
	if m.seat_number != nil {
		fields = append(fields, flightseat.FieldSeatNumber)
	}
	if m.price != nil {
		fields = append(fields, flightseat.FieldPrice)
	}
	if m.passenger_id != nil {
		fields = append(fields, flightseat.FieldPassengerID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FlightSeatMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case flightseat.FieldFlightID:
		return m.FlightID()
	case flightseat.FieldSeatNumber:
		return m.SeatNumber()
	case flightseat.FieldPrice:
		return m.Price()
	case flightseat.FieldPassengerID:
		return m.PassengerID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FlightSeatMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case flightseat.FieldFlightID:
		return m.OldFlightID(ctx)
	case flightseat.FieldSeatNumber:
		return m.OldSeatNumber(ctx)
	case flightseat.FieldPrice:
		return m.OldPrice(ctx)
	case flightseat.FieldPassengerID:
		return m.OldPassengerID(ctx)
	}
	return nil, fmt.Errorf("unknown FlightSeat field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlightSeatMutation) SetField(name string, value ent.Value) error {
	switch name {
	case flightseat.FieldFlightID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFlightID(v)
		return nil
	case flightseat.FieldSeatNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeatNumber(v)
		return nil
	case flightseat.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	case flightseat.FieldPassengerID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassengerID(v)
		return nil
	}
	return fmt.Errorf("unknown FlightSeat field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FlightSeatMutation) AddedFields() []string {
	var fields []string
	if m.addprice != nil {
		fields = append(fields, flightseat.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FlightSeatMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case flightseat.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlightSeatMutation) AddField(name string, value ent.Value) error {
	switch name {
	case flightseat.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown FlightSeat numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FlightSeatMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(flightseat.FieldPassengerID) {
		fields = append(fields, flightseat.FieldPassengerID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FlightSeatMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FlightSeatMutation) ClearField(name string) error {
	switch name {
	case flightseat.FieldPassengerID:
		m.ClearPassengerID()
		return nil
	}
	return fmt.Errorf("unknown FlightSeat nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FlightSeatMutation) ResetField(name string) error {
	switch name {
	case flightseat.FieldFlightID:
		m.ResetFlightID()
		return nil
	case flightseat.FieldSeatNumber:
		m.ResetSeatNumber()
		return nil
	case flightseat.FieldPrice:
		m.ResetPrice()
		return nil
	case flightseat.FieldPassengerID:
		m.ResetPassengerID()
		return nil
	}
	return fmt.Errorf("unknown FlightSeat field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FlightSeatMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.flight != nil {
		edges = append(edges, flightseat.EdgeFlight)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FlightSeatMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case flightseat.EdgeFlight:
		if id := m.flight; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FlightSeatMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FlightSeatMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FlightSeatMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedflight {
		edges = append(edges, flightseat.EdgeFlight)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FlightSeatMutation) EdgeCleared(name string) bool {
	switch name {
	case flightseat.EdgeFlight:
		return m.clearedflight
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FlightSeatMutation) ClearEdge(name string) error {
	switch name {
	case flightseat.EdgeFlight:
		m.ClearFlight()
		return nil
	}
	return fmt.Errorf("unknown FlightSeat unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FlightSeatMutation) ResetEdge(name string) error {
	switch name {
	case flightseat.EdgeFlight:
		m.ResetFlight()
		return nil
	}
	return fmt.Errorf("unknown FlightSeat edge %s", name)
}

// TicketMutation represents an operation that mutates the Ticket nodes in the graph.
type TicketMutation struct {
	config
	op            Op
	typ           string
	id            *string
	passenger_id  *string
	seat          *string
	price         *float64
	addprice      *float64
	clearedFields map[string]struct{}
	flight        *string
	clearedflight bool
	done          bool
	oldValue      func(context.Context) (*Ticket, error)
	predicates    []predicate.Ticket
}

var _ ent.Mutation = (*TicketMutation)(nil)

// ticketOption allows management of the mutation configuration using functional options.
type ticketOption func(*TicketMutation)

// newTicketMutation creates new mutation for the Ticket entity.
func newTicketMutation(c config, op Op, opts ...ticketOption) *TicketMutation {
	m := &TicketMutation{
		config:        c,
		op:            op,
		typ:           TypeTicket,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTicketID sets the ID field of the mutation.
func withTicketID(id string) ticketOption {
	return func(m *TicketMutation) {
		var (
			err   error
			once  sync.Once
			value *Ticket
		)
		m.oldValue = func(ctx context.Context) (*Ticket, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Ticket.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTicket sets the old Ticket of the mutation.
func withTicket(node *Ticket) ticketOption {
	return func(m *TicketMutation) {
		m.oldValue = func(context.Context) (*Ticket, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TicketMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TicketMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Ticket entities.
func (m *TicketMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TicketMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TicketMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Ticket.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPassengerID sets the "passenger_id" field.
func (m *TicketMutation) SetPassengerID(s string) {
	m.passenger_id = &s
}

// PassengerID returns the value of the "passenger_id" field in the mutation.
func (m *TicketMutation) PassengerID() (r string, exists bool) {
	v := m.passenger_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPassengerID returns the old "passenger_id" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldPassengerID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassengerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassengerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassengerID: %w", err)
	}
	return oldValue.PassengerID, nil
}

// ResetPassengerID resets all changes to the "passenger_id" field.
func (m *TicketMutation) ResetPassengerID() {
	m.passenger_id = nil
}

// SetSeat sets the "seat" field.
func (m *TicketMutation) SetSeat(s string) {
	m.seat = &s
}

// Seat returns the value of the "seat" field in the mutation.
func (m *TicketMutation) Seat() (r string, exists bool) {
	v := m.seat
	if v == nil {
		return
	}
	return *v, true
}

// OldSeat returns the old "seat" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldSeat(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeat is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeat requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeat: %w", err)
	}
	return oldValue.Seat, nil
}

// ResetSeat resets all changes to the "seat" field.
func (m *TicketMutation) ResetSeat() {
	m.seat = nil
}

// SetPrice sets the "price" field.
func (m *TicketMutation) SetPrice(f float64) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *TicketMutation) Price() (r float64, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *TicketMutation) AddPrice(f float64) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *TicketMutation) AddedPrice() (r float64, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *TicketMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// SetFlightID sets the "flight" edge to the Flight entity by id.
func (m *TicketMutation) SetFlightID(id string) {
	m.flight = &id
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (m *TicketMutation) ClearFlight() {
	m.clearedflight = true
}

// FlightCleared reports if the "flight" edge to the Flight entity was cleared.
func (m *TicketMutation) FlightCleared() bool {
	return m.clearedflight
}

// FlightID returns the "flight" edge ID in the mutation.
func (m *TicketMutation) FlightID() (id string, exists bool) {
	if m.flight != nil {
		return *m.flight, true
	}
	return
}

// FlightIDs returns the "flight" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// FlightID instead. It exists only for internal usage by the builders.
func (m *TicketMutation) FlightIDs() (ids []string) {
	if id := m.flight; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetFlight resets all changes to the "flight" edge.
func (m *TicketMutation) ResetFlight() {
	m.flight = nil
	m.clearedflight = false
}

// Where appends a list predicates to the TicketMutation builder.
func (m *TicketMutation) Where(ps ...predicate.Ticket) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TicketMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TicketMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Ticket, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TicketMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TicketMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Ticket).
func (m *TicketMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TicketMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.passenger_id != nil {
		fields = append(fields, ticket.FieldPassengerID)
	}
	if m.seat != nil {
		fields = append(fields, ticket.FieldSeat)
	}
	if m.price != nil {
		fields = append(fields, ticket.FieldPrice)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TicketMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ticket.FieldPassengerID:
		return m.PassengerID()
	case ticket.FieldSeat:
		return m.Seat()
	case ticket.FieldPrice:
		return m.Price()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TicketMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case ticket.FieldPassengerID:
		return m.OldPassengerID(ctx)
	case ticket.FieldSeat:
		return m.OldSeat(ctx)
	case ticket.FieldPrice:
		return m.OldPrice(ctx)
	}
	return nil, fmt.Errorf("unknown Ticket field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TicketMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ticket.FieldPassengerID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassengerID(v)
		return nil
	case ticket.FieldSeat:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeat(v)
		return nil
	case ticket.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	}
	return fmt.Errorf("unknown Ticket field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TicketMutation) AddedFields() []string {
	var fields []string
	if m.addprice != nil {
		fields = append(fields, ticket.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TicketMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case ticket.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TicketMutation) AddField(name string, value ent.Value) error {
	switch name {
	case ticket.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown Ticket numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TicketMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TicketMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TicketMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Ticket nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TicketMutation) ResetField(name string) error {
	switch name {
	case ticket.FieldPassengerID:
		m.ResetPassengerID()
		return nil
	case ticket.FieldSeat:
		m.ResetSeat()
		return nil
	case ticket.FieldPrice:
		m.ResetPrice()
		return nil
	}
	return fmt.Errorf("unknown Ticket field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TicketMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.flight != nil {
		edges = append(edges, ticket.EdgeFlight)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TicketMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case ticket.EdgeFlight:
		if id := m.flight; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TicketMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TicketMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TicketMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedflight {
		edges = append(edges, ticket.EdgeFlight)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TicketMutation) EdgeCleared(name string) bool {
	switch name {
	case ticket.EdgeFlight:
		return m.clearedflight
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TicketMutation) ClearEdge(name string) error {
	switch name {
	case ticket.EdgeFlight:
		m.ClearFlight()
		return nil
	}
	return fmt.Errorf("unknown Ticket unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TicketMutation) ResetEdge(name string) error {
	switch name {
	case ticket.EdgeFlight:
		m.ResetFlight()
		return nil
	}
	return fmt.Errorf("unknown Ticket edge %s", name)
}
