// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/aircraft"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flightseat"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/ticket"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aircraftFields := schema.Aircraft{}.Fields()
	_ = aircraftFields
	// aircraftDescID is the schema descriptor for id field.
	aircraftDescID := aircraftFields[0].Descriptor()
	// aircraft.IDValidator is a validator for the "id" field. It is called by the builders before save.
	aircraft.IDValidator = func() func(string) error {
		validators := aircraftDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	flightFields := schema.Flight{}.Fields()
	_ = flightFields
	// flightDescOrigin is the schema descriptor for origin field.
	flightDescOrigin := flightFields[1].Descriptor()
	// flight.OriginValidator is a validator for the "origin" field. It is called by the builders before save.
	flight.OriginValidator = flightDescOrigin.Validators[0].(func(string) error)
	// flightDescDestination is the schema descriptor for destination field.
	flightDescDestination := flightFields[2].Descriptor()
	// flight.DestinationValidator is a validator for the "destination" field. It is called by the builders before save.
	flight.DestinationValidator = flightDescDestination.Validators[0].(func(string) error)
	flightseatFields := schema.FlightSeat{}.Fields()
	_ = flightseatFields
	// flightseatDescSeatNumber is the schema descriptor for seat_number field.
	flightseatDescSeatNumber := flightseatFields[1].Descriptor()
	// flightseat.SeatNumberValidator is a validator for the "seat_number" field. It is called by the builders before save.
	flightseat.SeatNumberValidator = flightseatDescSeatNumber.Validators[0].(func(string) error)
	ticketFields := schema.Ticket{}.Fields()
	_ = ticketFields
	// ticketDescPassengerID is the schema descriptor for passenger_id field.
	ticketDescPassengerID := ticketFields[1].Descriptor()
	// ticket.PassengerIDValidator is a validator for the "passenger_id" field. It is called by the builders before save.
	ticket.PassengerIDValidator = ticketDescPassengerID.Validators[0].(func(string) error)
	// ticketDescSeat is the schema descriptor for seat field.
	ticketDescSeat := ticketFields[2].Descriptor()
	// ticket.SeatValidator is a validator for the "seat" field. It is called by the builders before save.
	ticket.SeatValidator = ticketDescSeat.Validators[0].(func(string) error)
}
