// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/ticket"
)

// TicketCreate is the builder for creating a Ticket entity.
type TicketCreate struct {
	config
	mutation *TicketMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPassengerID sets the "passenger_id" field.
func (_c *TicketCreate) SetPassengerID(v string) *TicketCreate {
	_c.mutation.SetPassengerID(v)
	return _c
}

// SetSeat sets the "seat" field.
func (_c *TicketCreate) SetSeat(v string) *TicketCreate {
	_c.mutation.SetSeat(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *TicketCreate) SetPrice(v float64) *TicketCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TicketCreate) SetID(v string) *TicketCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (_c *TicketCreate) SetFlightID(id string) *TicketCreate {
	_c.mutation.SetFlightID(id)
	return _c
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_c *TicketCreate) SetFlight(v *Flight) *TicketCreate {
	return _c.SetFlightID(v.ID)
}

// Mutation returns the TicketMutation object of the builder.
func (_c *TicketCreate) Mutation() *TicketMutation {
	return _c.mutation
}

// Save creates the Ticket in the database.
func (_c *TicketCreate) Save(ctx context.Context) (*Ticket, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketCreate) SaveX(ctx context.Context) *Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketCreate) check() error {
	if _, ok := _c.mutation.PassengerID(); !ok {
		return &ValidationError{Name: "passenger_id", err: errors.New(`ent: missing required field "Ticket.passenger_id"`)}
	}
	if v, ok := _c.mutation.PassengerID(); ok {
		if err := ticket.PassengerIDValidator(v); err != nil {
			return &ValidationError{Name: "passenger_id", err: fmt.Errorf(`ent: validator failed for field "Ticket.passenger_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Seat(); !ok {
		return &ValidationError{Name: "seat", err: errors.New(`ent: missing required field "Ticket.seat"`)}
	}
	if v, ok := _c.mutation.Seat(); ok {
		if err := ticket.SeatValidator(v); err != nil {
			return &ValidationError{Name: "seat", err: fmt.Errorf(`ent: validator failed for field "Ticket.seat": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Ticket.price"`)}
	}
	if len(_c.mutation.FlightIDs()) == 0 {
		return &ValidationError{Name: "flight", err: errors.New(`ent: missing required edge "Ticket.flight"`)}
	}
	return nil
}

func (_c *TicketCreate) sqlSave(ctx context.Context) (*Ticket, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Ticket.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketCreate) createSpec() (*Ticket, *sqlgraph.CreateSpec) {
	var (
		_node = &Ticket{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticket.Table, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PassengerID(); ok {
		_spec.SetField(ticket.FieldPassengerID, field.TypeString, value)
		_node.PassengerID = value
	}
	if value, ok := _c.mutation.Seat(); ok {
		_spec.SetField(ticket.FieldSeat, field.TypeString, value)
		_node.Seat = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(ticket.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if nodes := _c.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.FlightTable,
			Columns: []string{ticket.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.flight_tickets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ticket.Create().
//		SetPassengerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketUpsert) {
//			SetPassengerID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketCreate) OnConflict(opts ...sql.ConflictOption) *TicketUpsertOne {
	_c.conflict = opts
	return &TicketUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketCreate) OnConflictColumns(columns ...string) *TicketUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketUpsertOne{
		create: _c,
	}
}

type (
	// TicketUpsertOne is the builder for "upsert"-ing
	//  one Ticket node.
	TicketUpsertOne struct {
		create *TicketCreate
	}

	// TicketUpsert is the "OnConflict" setter.
	TicketUpsert struct {
		*sql.UpdateSet
	}
)

// SetPassengerID sets the "passenger_id" field.
func (u *TicketUpsert) SetPassengerID(v string) *TicketUpsert {
	u.Set(ticket.FieldPassengerID, v)
	return u
}

// UpdatePassengerID sets the "passenger_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdatePassengerID() *TicketUpsert {
	u.SetExcluded(ticket.FieldPassengerID)
	return u
}

// SetSeat sets the "seat" field.
func (u *TicketUpsert) SetSeat(v string) *TicketUpsert {
	u.Set(ticket.FieldSeat, v)
	return u
}

// UpdateSeat sets the "seat" field to the value that was provided on create.
func (u *TicketUpsert) UpdateSeat() *TicketUpsert {
	u.SetExcluded(ticket.FieldSeat)
	return u
}

// SetPrice sets the "price" field.
func (u *TicketUpsert) SetPrice(v float64) *TicketUpsert {
	u.Set(ticket.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *TicketUpsert) UpdatePrice() *TicketUpsert {
	u.SetExcluded(ticket.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *TicketUpsert) AddPrice(v float64) *TicketUpsert {
	u.Add(ticket.FieldPrice, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ticket.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketUpsertOne) UpdateNewValues() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ticket.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketUpsertOne) Ignore() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketUpsertOne) DoNothing() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketCreate.OnConflict
// documentation for more info.
func (u *TicketUpsertOne) Update(set func(*TicketUpsert)) *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetPassengerID sets the "passenger_id" field.
func (u *TicketUpsertOne) SetPassengerID(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetPassengerID(v)
	})
}

// UpdatePassengerID sets the "passenger_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdatePassengerID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePassengerID()
	})
}

// SetSeat sets the "seat" field.
func (u *TicketUpsertOne) SetSeat(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetSeat(v)
	})
}

// UpdateSeat sets the "seat" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateSeat() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateSeat()
	})
}

// SetPrice sets the "price" field.
func (u *TicketUpsertOne) SetPrice(v float64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *TicketUpsertOne) AddPrice(v float64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdatePrice() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePrice()
	})
}

// Exec executes the query.
func (u *TicketUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TicketUpsertOne.ID is not supported by MySQL driver. Use TicketUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketCreateBulk is the builder for creating many Ticket entities in bulk.
type TicketCreateBulk struct {
	config
	err      error
	builders []*TicketCreate
	conflict []sql.ConflictOption
}

// Save creates the Ticket entities in the database.
func (_c *TicketCreateBulk) Save(ctx context.Context) ([]*Ticket, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ticket, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketCreateBulk) SaveX(ctx context.Context) []*Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ticket.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketUpsert) {
//			SetPassengerID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketUpsertBulk {
	_c.conflict = opts
	return &TicketUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketCreateBulk) OnConflictColumns(columns ...string) *TicketUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketUpsertBulk{
		create: _c,
	}
}

// TicketUpsertBulk is the builder for "upsert"-ing
// a bulk of Ticket nodes.
type TicketUpsertBulk struct {
	create *TicketCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ticket.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketUpsertBulk) UpdateNewValues() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ticket.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketUpsertBulk) Ignore() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketUpsertBulk) DoNothing() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketCreateBulk.OnConflict
// documentation for more info.
func (u *TicketUpsertBulk) Update(set func(*TicketUpsert)) *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetPassengerID sets the "passenger_id" field.
func (u *TicketUpsertBulk) SetPassengerID(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetPassengerID(v)
	})
}

// UpdatePassengerID sets the "passenger_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdatePassengerID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePassengerID()
	})
}

// SetSeat sets the "seat" field.
func (u *TicketUpsertBulk) SetSeat(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetSeat(v)
	})
}

// UpdateSeat sets the "seat" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateSeat() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateSeat()
	})
}

// SetPrice sets the "price" field.
func (u *TicketUpsertBulk) SetPrice(v float64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *TicketUpsertBulk) AddPrice(v float64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdatePrice() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePrice()
	})
}

// Exec executes the query.
func (u *TicketUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
