// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/flight"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/ticket"
)

// TicketUpdate is the builder for updating Ticket entities.
type TicketUpdate struct {
	config
	hooks    []Hook
	mutation *TicketMutation
}

// Where appends a list predicates to the TicketUpdate builder.
func (_u *TicketUpdate) Where(ps ...predicate.Ticket) *TicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPassengerID sets the "passenger_id" field.
func (_u *TicketUpdate) SetPassengerID(v string) *TicketUpdate {
	_u.mutation.SetPassengerID(v)
	return _u
}

// SetNillablePassengerID sets the "passenger_id" field if the given value is not nil.
func (_u *TicketUpdate) SetNillablePassengerID(v *string) *TicketUpdate {
	if v != nil {
		_u.SetPassengerID(*v)
	}
	return _u
}

// SetSeat sets the "seat" field.
func (_u *TicketUpdate) SetSeat(v string) *TicketUpdate {
	_u.mutation.SetSeat(v)
	return _u
}

// SetNillableSeat sets the "seat" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableSeat(v *string) *TicketUpdate {
	if v != nil {
		_u.SetSeat(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *TicketUpdate) SetPrice(v float64) *TicketUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *TicketUpdate) SetNillablePrice(v *float64) *TicketUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *TicketUpdate) AddPrice(v float64) *TicketUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (_u *TicketUpdate) SetFlightID(id string) *TicketUpdate {
	_u.mutation.SetFlightID(id)
	return _u
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_u *TicketUpdate) SetFlight(v *Flight) *TicketUpdate {
	return _u.SetFlightID(v.ID)
}

// Mutation returns the TicketMutation object of the builder.
func (_u *TicketUpdate) Mutation() *TicketMutation {
	return _u.mutation
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (_u *TicketUpdate) ClearFlight() *TicketUpdate {
	_u.mutation.ClearFlight()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketUpdate) check() error {
	if v, ok := _u.mutation.PassengerID(); ok {
		if err := ticket.PassengerIDValidator(v); err != nil {
			return &ValidationError{Name: "passenger_id", err: fmt.Errorf(`ent: validator failed for field "Ticket.passenger_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Seat(); ok {
		if err := ticket.SeatValidator(v); err != nil {
			return &ValidationError{Name: "seat", err: fmt.Errorf(`ent: validator failed for field "Ticket.seat": %w`, err)}
		}
	}
	if _u.mutation.FlightCleared() && len(_u.mutation.FlightIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ticket.flight"`)
	}
	return nil
}

func (_u *TicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticket.Table, ticket.Columns, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PassengerID(); ok {
		_spec.SetField(ticket.FieldPassengerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seat(); ok {
		_spec.SetField(ticket.FieldSeat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(ticket.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(ticket.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.FlightCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.FlightTable,
			Columns: []string{ticket.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.FlightTable,
			Columns: []string{ticket.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketUpdateOne is the builder for updating a single Ticket entity.
type TicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketMutation
}

// SetPassengerID sets the "passenger_id" field.
func (_u *TicketUpdateOne) SetPassengerID(v string) *TicketUpdateOne {
	_u.mutation.SetPassengerID(v)
	return _u
}

// SetNillablePassengerID sets the "passenger_id" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillablePassengerID(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetPassengerID(*v)
	}
	return _u
}

// SetSeat sets the "seat" field.
func (_u *TicketUpdateOne) SetSeat(v string) *TicketUpdateOne {
	_u.mutation.SetSeat(v)
	return _u
}

// SetNillableSeat sets the "seat" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableSeat(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetSeat(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *TicketUpdateOne) SetPrice(v float64) *TicketUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillablePrice(v *float64) *TicketUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *TicketUpdateOne) AddPrice(v float64) *TicketUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (_u *TicketUpdateOne) SetFlightID(id string) *TicketUpdateOne {
	_u.mutation.SetFlightID(id)
	return _u
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_u *TicketUpdateOne) SetFlight(v *Flight) *TicketUpdateOne {
	return _u.SetFlightID(v.ID)
}

// Mutation returns the TicketMutation object of the builder.
func (_u *TicketUpdateOne) Mutation() *TicketMutation {
	return _u.mutation
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (_u *TicketUpdateOne) ClearFlight() *TicketUpdateOne {
	_u.mutation.ClearFlight()
	return _u
}

// Where appends a list predicates to the TicketUpdate builder.
func (_u *TicketUpdateOne) Where(ps ...predicate.Ticket) *TicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketUpdateOne) Select(field string, fields ...string) *TicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ticket entity.
func (_u *TicketUpdateOne) Save(ctx context.Context) (*Ticket, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketUpdateOne) SaveX(ctx context.Context) *Ticket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketUpdateOne) check() error {
	if v, ok := _u.mutation.PassengerID(); ok {
		if err := ticket.PassengerIDValidator(v); err != nil {
			return &ValidationError{Name: "passenger_id", err: fmt.Errorf(`ent: validator failed for field "Ticket.passenger_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Seat(); ok {
		if err := ticket.SeatValidator(v); err != nil {
			return &ValidationError{Name: "seat", err: fmt.Errorf(`ent: validator failed for field "Ticket.seat": %w`, err)}
		}
	}
	if _u.mutation.FlightCleared() && len(_u.mutation.FlightIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ticket.flight"`)
	}
	return nil
}

func (_u *TicketUpdateOne) sqlSave(ctx context.Context) (_node *Ticket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticket.Table, ticket.Columns, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ticket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticket.FieldID)
		for _, f := range fields {
			if !ticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PassengerID(); ok {
		_spec.SetField(ticket.FieldPassengerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seat(); ok {
		_spec.SetField(ticket.FieldSeat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(ticket.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(ticket.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.FlightCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.FlightTable,
			Columns: []string{ticket.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.FlightTable,
			Columns: []string{ticket.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ticket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
