// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Aircraft is the predicate function for aircraft builders.
type Aircraft func(*sql.Selector)

// Flight is the predicate function for flight builders.
type Flight func(*sql.Selector)

// FlightSeat is the predicate function for flightseat builders.
type FlightSeat func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)
