// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AircraftsColumns holds the columns for the "aircrafts" table.
	AircraftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 20},
		{Name: "seats", Type: field.TypeJSON},
	}
	// AircraftsTable holds the schema information for the "aircrafts" table.
	AircraftsTable = &schema.Table{
		Name:       "aircrafts",
		Columns:    AircraftsColumns,
		PrimaryKey: []*schema.Column{AircraftsColumns[0]},
	}
	// FlightsColumns holds the columns for the "flights" table.
	FlightsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "origin", Type: field.TypeString},
		{Name: "destination", Type: field.TypeString},
		{Name: "scheduled_departure", Type: field.TypeTime},
		{Name: "scheduled_arrival", Type: field.TypeTime},
		{Name: "close_booking_buffer_ns", Type: field.TypeInt64},
		{Name: "aircraft_flights", Type: field.TypeString, Size: 20},
	}
	// FlightsTable holds the schema information for the "flights" table.
	FlightsTable = &schema.Table{
		Name:       "flights",
		Columns:    FlightsColumns,
		PrimaryKey: []*schema.Column{FlightsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "flights_aircrafts_flights",
				Columns:    []*schema.Column{FlightsColumns[6]},
				RefColumns: []*schema.Column{AircraftsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// FlightSeatsColumns holds the columns for the "flight_seats" table.
	FlightSeatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "seat_number", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "passenger_id", Type: field.TypeString, Nullable: true},
		{Name: "flight_id", Type: field.TypeString},
	}
	// FlightSeatsTable holds the schema information for the "flight_seats" table.
	FlightSeatsTable = &schema.Table{
		Name:       "flight_seats",
		Columns:    FlightSeatsColumns,
		PrimaryKey: []*schema.Column{FlightSeatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "flight_seats_flights_seats",
				Columns:    []*schema.Column{FlightSeatsColumns[4]},
				RefColumns: []*schema.Column{FlightsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "flightseat_flight_id_seat_number",
				Unique:  true,
				Columns: []*schema.Column{FlightSeatsColumns[4], FlightSeatsColumns[1]},
			},
		},
	}
	// TicketsColumns holds the columns for the "tickets" table.
	TicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "passenger_id", Type: field.TypeString},
		{Name: "seat", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "flight_tickets", Type: field.TypeString},
	}
	// TicketsTable holds the schema information for the "tickets" table.
	TicketsTable = &schema.Table{
		Name:       "tickets",
		Columns:    TicketsColumns,
		PrimaryKey: []*schema.Column{TicketsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tickets_flights_tickets",
				Columns:    []*schema.Column{TicketsColumns[4]},
				RefColumns: []*schema.Column{FlightsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AircraftsTable,
		FlightsTable,
		FlightSeatsTable,
		TicketsTable,
	}
)

func init() {
	FlightsTable.ForeignKeys[0].RefTable = AircraftsTable
	FlightSeatsTable.ForeignKeys[0].RefTable = FlightsTable
	TicketsTable.ForeignKeys[0].RefTable = FlightsTable
}
