// Code generated by ent, DO NOT EDIT.

package aircraft

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the aircraft type in the database.
	Label = "aircraft"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSeats holds the string denoting the seats field in the database.
	FieldSeats = "seats"
	// EdgeFlights holds the string denoting the flights edge name in mutations.
	EdgeFlights = "flights"
	// Table holds the table name of the aircraft in the database.
	Table = "aircrafts"
	// FlightsTable is the table that holds the flights relation/edge.
	FlightsTable = "flights"
	// FlightsInverseTable is the table name for the Flight entity.
	// It exists in this package in order to avoid circular dependency with the "flight" package.
	FlightsInverseTable = "flights"
	// FlightsColumn is the table column denoting the flights relation/edge.
	FlightsColumn = "aircraft_flights"
)

// Columns holds all SQL columns for aircraft fields.
var Columns = []string{
	FieldID,
	FieldSeats,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Aircraft queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFlightsCount orders the results by flights count.
func ByFlightsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFlightsStep(), opts...)
	}
}

// ByFlights orders the results by flights terms.
func ByFlights(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlightsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFlightsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlightsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FlightsTable, FlightsColumn),
	)
}
