// Code generated by ent, DO NOT EDIT.

package aircraft

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldContainsFold(FieldID, id))
}

// HasFlights applies the HasEdge predicate on the "flights" edge.
func HasFlights() predicate.Aircraft {
	return predicate.Aircraft(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FlightsTable, FlightsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlightsWith applies the HasEdge predicate on the "flights" edge with a given conditions (other predicates).
func HasFlightsWith(preds ...predicate.Flight) predicate.Aircraft {
	return predicate.Aircraft(func(s *sql.Selector) {
		step := newFlightsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Aircraft) predicate.Aircraft {
	return predicate.Aircraft(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Aircraft) predicate.Aircraft {
	return predicate.Aircraft(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Aircraft) predicate.Aircraft {
	return predicate.Aircraft(sql.NotPredicates(p))
}
