// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ticket type in the database.
	Label = "ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPassengerID holds the string denoting the passenger_id field in the database.
	FieldPassengerID = "passenger_id"
	// FieldSeat holds the string denoting the seat field in the database.
	FieldSeat = "seat"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// EdgeFlight holds the string denoting the flight edge name in mutations.
	EdgeFlight = "flight"
	// Table holds the table name of the ticket in the database.
	Table = "tickets"
	// FlightTable is the table that holds the flight relation/edge.
	FlightTable = "tickets"
	// FlightInverseTable is the table name for the Flight entity.
	// It exists in this package in order to avoid circular dependency with the "flight" package.
	FlightInverseTable = "flights"
	// FlightColumn is the table column denoting the flight relation/edge.
	FlightColumn = "flight_tickets"
)

// Columns holds all SQL columns for ticket fields.
var Columns = []string{
	FieldID,
	FieldPassengerID,
	FieldSeat,
	FieldPrice,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tickets"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"flight_tickets",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// PassengerIDValidator is a validator for the "passenger_id" field. It is called by the builders before save.
	PassengerIDValidator func(string) error
	// SeatValidator is a validator for the "seat" field. It is called by the builders before save.
	SeatValidator func(string) error
)

// OrderOption defines the ordering options for the Ticket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPassengerID orders the results by the passenger_id field.
func ByPassengerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassengerID, opts...).ToFunc()
}

// BySeat orders the results by the seat field.
func BySeat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeat, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByFlightField orders the results by flight field.
func ByFlightField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlightStep(), sql.OrderByField(field, opts...))
	}
}
func newFlightStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlightInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FlightTable, FlightColumn),
	)
}
