// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldID, id))
}

// PassengerID applies equality check predicate on the "passenger_id" field. It's identical to PassengerIDEQ.
func PassengerID(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldPassengerID, v))
}

// Seat applies equality check predicate on the "seat" field. It's identical to SeatEQ.
func Seat(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSeat, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldPrice, v))
}

// PassengerIDEQ applies the EQ predicate on the "passenger_id" field.
func PassengerIDEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldPassengerID, v))
}

// PassengerIDNEQ applies the NEQ predicate on the "passenger_id" field.
func PassengerIDNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldPassengerID, v))
}

// PassengerIDIn applies the In predicate on the "passenger_id" field.
func PassengerIDIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldPassengerID, vs...))
}

// PassengerIDNotIn applies the NotIn predicate on the "passenger_id" field.
func PassengerIDNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldPassengerID, vs...))
}

// PassengerIDGT applies the GT predicate on the "passenger_id" field.
func PassengerIDGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldPassengerID, v))
}

// PassengerIDGTE applies the GTE predicate on the "passenger_id" field.
func PassengerIDGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldPassengerID, v))
}

// PassengerIDLT applies the LT predicate on the "passenger_id" field.
func PassengerIDLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldPassengerID, v))
}

// PassengerIDLTE applies the LTE predicate on the "passenger_id" field.
func PassengerIDLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldPassengerID, v))
}

// PassengerIDContains applies the Contains predicate on the "passenger_id" field.
func PassengerIDContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldPassengerID, v))
}

// PassengerIDHasPrefix applies the HasPrefix predicate on the "passenger_id" field.
func PassengerIDHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldPassengerID, v))
}

// PassengerIDHasSuffix applies the HasSuffix predicate on the "passenger_id" field.
func PassengerIDHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldPassengerID, v))
}

// PassengerIDEqualFold applies the EqualFold predicate on the "passenger_id" field.
func PassengerIDEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldPassengerID, v))
}

// PassengerIDContainsFold applies the ContainsFold predicate on the "passenger_id" field.
func PassengerIDContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldPassengerID, v))
}

// SeatEQ applies the EQ predicate on the "seat" field.
func SeatEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSeat, v))
}

// SeatNEQ applies the NEQ predicate on the "seat" field.
func SeatNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldSeat, v))
}

// SeatIn applies the In predicate on the "seat" field.
func SeatIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldSeat, vs...))
}

// SeatNotIn applies the NotIn predicate on the "seat" field.
func SeatNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldSeat, vs...))
}

// SeatGT applies the GT predicate on the "seat" field.
func SeatGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldSeat, v))
}

// SeatGTE applies the GTE predicate on the "seat" field.
func SeatGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldSeat, v))
}

// SeatLT applies the LT predicate on the "seat" field.
func SeatLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldSeat, v))
}

// SeatLTE applies the LTE predicate on the "seat" field.
func SeatLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldSeat, v))
}

// SeatContains applies the Contains predicate on the "seat" field.
func SeatContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldSeat, v))
}

// SeatHasPrefix applies the HasPrefix predicate on the "seat" field.
func SeatHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldSeat, v))
}

// SeatHasSuffix applies the HasSuffix predicate on the "seat" field.
func SeatHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldSeat, v))
}

// SeatEqualFold applies the EqualFold predicate on the "seat" field.
func SeatEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldSeat, v))
}

// SeatContainsFold applies the ContainsFold predicate on the "seat" field.
func SeatContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldSeat, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldPrice, v))
}

// HasFlight applies the HasEdge predicate on the "flight" edge.
func HasFlight() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FlightTable, FlightColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlightWith applies the HasEdge predicate on the "flight" edge with a given conditions (other predicates).
func HasFlightWith(preds ...predicate.Flight) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newFlightStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.NotPredicates(p))
}
