// Code generated by ent, DO NOT EDIT.

package flightseat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the flightseat type in the database.
	Label = "flight_seat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFlightID holds the string denoting the flight_id field in the database.
	FieldFlightID = "flight_id"
	// FieldSeatNumber holds the string denoting the seat_number field in the database.
	FieldSeatNumber = "seat_number"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldPassengerID holds the string denoting the passenger_id field in the database.
	FieldPassengerID = "passenger_id"
	// EdgeFlight holds the string denoting the flight edge name in mutations.
	EdgeFlight = "flight"
	// Table holds the table name of the flightseat in the database.
	Table = "flight_seats"
	// FlightTable is the table that holds the flight relation/edge.
	FlightTable = "flight_seats"
	// FlightInverseTable is the table name for the Flight entity.
	// It exists in this package in order to avoid circular dependency with the "flight" package.
	FlightInverseTable = "flights"
	// FlightColumn is the table column denoting the flight relation/edge.
	FlightColumn = "flight_id"
)

// Columns holds all SQL columns for flightseat fields.
var Columns = []string{
	FieldID,
	FieldFlightID,
	FieldSeatNumber,
	FieldPrice,
	FieldPassengerID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SeatNumberValidator is a validator for the "seat_number" field. It is called by the builders before save.
	SeatNumberValidator func(string) error
)

// OrderOption defines the ordering options for the FlightSeat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFlightID orders the results by the flight_id field.
func ByFlightID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlightID, opts...).ToFunc()
}

// BySeatNumber orders the results by the seat_number field.
func BySeatNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeatNumber, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByPassengerID orders the results by the passenger_id field.
func ByPassengerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassengerID, opts...).ToFunc()
}

// ByFlightField orders the results by flight field.
func ByFlightField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlightStep(), sql.OrderByField(field, opts...))
	}
}
func newFlightStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlightInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FlightTable, FlightColumn),
	)
}
