// Code generated by ent, DO NOT EDIT.

package flightseat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/allexborysov/aircraft/internal/infrastructure/storage/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLTE(FieldID, id))
}

// FlightID applies equality check predicate on the "flight_id" field. It's identical to FlightIDEQ.
func FlightID(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldFlightID, v))
}

// SeatNumber applies equality check predicate on the "seat_number" field. It's identical to SeatNumberEQ.
func SeatNumber(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldSeatNumber, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldPrice, v))
}

// PassengerID applies equality check predicate on the "passenger_id" field. It's identical to PassengerIDEQ.
func PassengerID(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldPassengerID, v))
}

// FlightIDEQ applies the EQ predicate on the "flight_id" field.
func FlightIDEQ(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldFlightID, v))
}

// FlightIDNEQ applies the NEQ predicate on the "flight_id" field.
func FlightIDNEQ(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNEQ(FieldFlightID, v))
}

// FlightIDIn applies the In predicate on the "flight_id" field.
func FlightIDIn(vs ...string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldIn(FieldFlightID, vs...))
}

// FlightIDNotIn applies the NotIn predicate on the "flight_id" field.
func FlightIDNotIn(vs ...string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNotIn(FieldFlightID, vs...))
}

// FlightIDGT applies the GT predicate on the "flight_id" field.
func FlightIDGT(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGT(FieldFlightID, v))
}

// FlightIDGTE applies the GTE predicate on the "flight_id" field.
func FlightIDGTE(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGTE(FieldFlightID, v))
}

// FlightIDLT applies the LT predicate on the "flight_id" field.
func FlightIDLT(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLT(FieldFlightID, v))
}

// FlightIDLTE applies the LTE predicate on the "flight_id" field.
func FlightIDLTE(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLTE(FieldFlightID, v))
}

// FlightIDContains applies the Contains predicate on the "flight_id" field.
func FlightIDContains(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldContains(FieldFlightID, v))
}

// FlightIDHasPrefix applies the HasPrefix predicate on the "flight_id" field.
func FlightIDHasPrefix(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldHasPrefix(FieldFlightID, v))
}

// FlightIDHasSuffix applies the HasSuffix predicate on the "flight_id" field.
func FlightIDHasSuffix(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldHasSuffix(FieldFlightID, v))
}

// FlightIDEqualFold applies the EqualFold predicate on the "flight_id" field.
func FlightIDEqualFold(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEqualFold(FieldFlightID, v))
}

// FlightIDContainsFold applies the ContainsFold predicate on the "flight_id" field.
func FlightIDContainsFold(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldContainsFold(FieldFlightID, v))
}

// SeatNumberEQ applies the EQ predicate on the "seat_number" field.
func SeatNumberEQ(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldSeatNumber, v))
}

// SeatNumberNEQ applies the NEQ predicate on the "seat_number" field.
func SeatNumberNEQ(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNEQ(FieldSeatNumber, v))
}

// SeatNumberIn applies the In predicate on the "seat_number" field.
func SeatNumberIn(vs ...string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldIn(FieldSeatNumber, vs...))
}

// SeatNumberNotIn applies the NotIn predicate on the "seat_number" field.
func SeatNumberNotIn(vs ...string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNotIn(FieldSeatNumber, vs...))
}

// SeatNumberGT applies the GT predicate on the "seat_number" field.
func SeatNumberGT(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGT(FieldSeatNumber, v))
}

// SeatNumberGTE applies the GTE predicate on the "seat_number" field.
func SeatNumberGTE(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGTE(FieldSeatNumber, v))
}

// SeatNumberLT applies the LT predicate on the "seat_number" field.
func SeatNumberLT(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLT(FieldSeatNumber, v))
}

// SeatNumberLTE applies the LTE predicate on the "seat_number" field.
func SeatNumberLTE(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLTE(FieldSeatNumber, v))
}

// SeatNumberContains applies the Contains predicate on the "seat_number" field.
func SeatNumberContains(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldContains(FieldSeatNumber, v))
}

// SeatNumberHasPrefix applies the HasPrefix predicate on the "seat_number" field.
func SeatNumberHasPrefix(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldHasPrefix(FieldSeatNumber, v))
}

// SeatNumberHasSuffix applies the HasSuffix predicate on the "seat_number" field.
func SeatNumberHasSuffix(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldHasSuffix(FieldSeatNumber, v))
}

// SeatNumberEqualFold applies the EqualFold predicate on the "seat_number" field.
func SeatNumberEqualFold(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEqualFold(FieldSeatNumber, v))
}

// SeatNumberContainsFold applies the ContainsFold predicate on the "seat_number" field.
func SeatNumberContainsFold(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldContainsFold(FieldSeatNumber, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLTE(FieldPrice, v))
}

// PassengerIDEQ applies the EQ predicate on the "passenger_id" field.
func PassengerIDEQ(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEQ(FieldPassengerID, v))
}

// PassengerIDNEQ applies the NEQ predicate on the "passenger_id" field.
func PassengerIDNEQ(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNEQ(FieldPassengerID, v))
}

// PassengerIDIn applies the In predicate on the "passenger_id" field.
func PassengerIDIn(vs ...string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldIn(FieldPassengerID, vs...))
}

// PassengerIDNotIn applies the NotIn predicate on the "passenger_id" field.
func PassengerIDNotIn(vs ...string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNotIn(FieldPassengerID, vs...))
}

// PassengerIDGT applies the GT predicate on the "passenger_id" field.
func PassengerIDGT(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGT(FieldPassengerID, v))
}

// PassengerIDGTE applies the GTE predicate on the "passenger_id" field.
func PassengerIDGTE(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldGTE(FieldPassengerID, v))
}

// PassengerIDLT applies the LT predicate on the "passenger_id" field.
func PassengerIDLT(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLT(FieldPassengerID, v))
}

// PassengerIDLTE applies the LTE predicate on the "passenger_id" field.
func PassengerIDLTE(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldLTE(FieldPassengerID, v))
}

// PassengerIDContains applies the Contains predicate on the "passenger_id" field.
func PassengerIDContains(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldContains(FieldPassengerID, v))
}

// PassengerIDHasPrefix applies the HasPrefix predicate on the "passenger_id" field.
func PassengerIDHasPrefix(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldHasPrefix(FieldPassengerID, v))
}

// PassengerIDHasSuffix applies the HasSuffix predicate on the "passenger_id" field.
func PassengerIDHasSuffix(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldHasSuffix(FieldPassengerID, v))
}

// PassengerIDIsNil applies the IsNil predicate on the "passenger_id" field.
func PassengerIDIsNil() predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldIsNull(FieldPassengerID))
}

// PassengerIDNotNil applies the NotNil predicate on the "passenger_id" field.
func PassengerIDNotNil() predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldNotNull(FieldPassengerID))
}

// PassengerIDEqualFold applies the EqualFold predicate on the "passenger_id" field.
func PassengerIDEqualFold(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldEqualFold(FieldPassengerID, v))
}

// PassengerIDContainsFold applies the ContainsFold predicate on the "passenger_id" field.
func PassengerIDContainsFold(v string) predicate.FlightSeat {
	return predicate.FlightSeat(sql.FieldContainsFold(FieldPassengerID, v))
}

// HasFlight applies the HasEdge predicate on the "flight" edge.
func HasFlight() predicate.FlightSeat {
	return predicate.FlightSeat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FlightTable, FlightColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlightWith applies the HasEdge predicate on the "flight" edge with a given conditions (other predicates).
func HasFlightWith(preds ...predicate.Flight) predicate.FlightSeat {
	return predicate.FlightSeat(func(s *sql.Selector) {
		step := newFlightStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FlightSeat) predicate.FlightSeat {
	return predicate.FlightSeat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FlightSeat) predicate.FlightSeat {
	return predicate.FlightSeat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FlightSeat) predicate.FlightSeat {
	return predicate.FlightSeat(sql.NotPredicates(p))
}
